import { type LessonContent } from "@/lessons/types";

export const BASIC_SYNTAX_LESSON: LessonContent = {
  slug: "basic-syntax",
  title: "Basic Syntax",
  subtitle: "Learn the building blocks that make Python code valid and readable.",
  sections: [
    { kind: "prose", heading: "Why this matters", body: ["Before a program can do useful work, Python needs to understand its structure. Comments, keywords, names, statements, and indentation are part of that structure.", "These rules are small, but they appear in almost every Python program."] },
    { kind: "animation", variant: "basic-syntax", caption: "How Python code is structured" },
    { kind: "prose", heading: "Comments", body: ["A comment is a note for people reading the code. Python ignores it when the program runs.", "Start a comment with `#`. Use comments to explain why a line exists when the reason is not obvious."] },
    { kind: "interactive-code", code: '# Calculate the final price after tax\nprice = 100\ntax = price * 0.08\nprint(price + tax)' },
    { kind: "prose", body: ["The first line is a comment. Python runs the remaining lines.", "A comment can also follow code on the same line, but use that form sparingly."] },
    { kind: "interactive-code", code: 'tax_rate = 0.08  # Current sales tax rate\nprint(tax_rate)' },
    { kind: "callout", tone: "warn", title: "Comments and triple-quoted strings", body: "`#` is Python's comment syntax. Triple-quoted text is a string. It is often used as a docstring directly inside a module, function, class, or method." },
    { kind: "prose", heading: "Docstrings", body: ["A docstring is a triple-quoted string placed first inside a function, class, or module. It records what that code is for.", "Python stores a function's docstring in its `__doc__` attribute."] },
    { kind: "interactive-code", code: 'def multiply(a, b):\n    """Return the product of a and b."""\n    return a * b\n\nprint(multiply.__doc__)' },
    { kind: "prose", heading: "Keywords", body: ["Keywords are words that Python reserves for its own grammar. `if`, `for`, `while`, `def`, `class`, and `return` are keywords.", "You cannot use a keyword as a variable, function, or class name."] },
    { kind: "interactive-code", code: 'import keyword\n\nprint(keyword.kwlist)' },
    { kind: "interactive-code", code: '# if = 10  # This would cause a SyntaxError\nuser_age = 10\nprint(user_age)' },
    { kind: "prose", heading: "Identifiers", body: ["An identifier is a name that you create in Python. Variables, functions, and classes all use identifiers.", "Identifiers can contain letters, digits, and underscores. They cannot start with a digit, contain spaces or hyphens, or be Python keywords."] },
    { kind: "table", caption: "Identifier rules", headers: ["Name", "Valid?", "Reason"], rows: [["customer_name", "Yes", "Letters and underscore"], ["order2", "Yes", "A digit is allowed after the first character"], ["2orders", "No", "Cannot start with a digit"], ["order-total", "No", "Hyphens are not allowed"], ["class", "No", "Python keyword"]] },
    { kind: "interactive-code", code: 'customer_name = "Ava"\nCustomer_name = "Noah"\n\nprint(customer_name)\nprint(Customer_name)' },
    { kind: "prose", body: ["Python is case-sensitive, so `customer_name` and `Customer_name` are different identifiers.", "For variables and functions, use `snake_case`, such as `total_price` and `calculate_salary`."] },
    { kind: "prose", heading: "Statements and expressions", body: ["A statement is an instruction Python executes. `total = price * quantity` is an assignment statement.", "An expression produces a value. In `total = price * quantity`, the part `price * quantity` is an expression."] },
    { kind: "interactive-code", code: 'price = 20\nquantity = 3\ntotal = price * quantity\n\nprint(total)' },
    { kind: "prose", body: ["Python usually runs statements from top to bottom. A condition, loop, or function can change that order."] },
    { kind: "prose", heading: "Writing long statements", body: ["A statement normally ends at a newline. Inside parentheses, brackets, and braces, Python lets you continue the statement on the next line."] },
    { kind: "interactive-code", code: 'total = (\n    10 + 20 +\n    30\n)\n\nprint(total)' },
    { kind: "prose", heading: "Indentation", body: ["Python uses indentation to mark a block of code. A block starts after a line ending in `:` and continues while the code stays indented.", "Use four spaces for each indentation level."] },
    { kind: "interactive-code", code: 'score = 75\n\nif score >= 50:\n    print("Passed")\n\nprint("Check complete")' },
    { kind: "callout", tone: "warn", title: "Common mistakes", body: "- **Missing indentation**: Code after `if`, `for`, `while`, `def`, and `class` must be indented.\n- **Using a keyword as a name**: `class = 1` is not valid Python.\n- **Mixing tabs and spaces**: Use four spaces consistently.\n- **Explaining obvious code**: Comments should add context, not repeat the line." },
    { kind: "takeaways", items: ["Comments are notes for people and begin with `#`.", "Keywords are reserved words in Python.", "Identifiers are the names you create.", "Statements are instructions. Expressions produce values.", "Indentation groups code into blocks."] },
    { kind: "quiz", questions: [
      { id: "basic-syntax-1", question: "What does Python do with a line that begins with `#`?", options: ["Ignores it as a comment", "Prints it", "Runs it twice", "Turns it into a variable"], correctIndex: 0, explanation: "A line beginning with `#` is a comment. Python ignores it during execution." },
      { id: "basic-syntax-2", question: "Which name is a valid Python identifier?", options: ["2_orders", "order-total", "class", "order_total"], correctIndex: 3, explanation: "`order_total` uses letters and an underscore, and it does not begin with a digit or use a keyword." },
      { id: "basic-syntax-3", question: "What is `price * quantity` in `total = price * quantity`?", options: ["A comment", "An expression", "A class", "A keyword"], correctIndex: 1, explanation: "It produces a value, so it is an expression. The full assignment line is a statement." },
      { id: "basic-syntax-4", question: "Why is indentation required after an `if` statement?", options: ["It marks the code that belongs to the if block", "It changes text color", "It adds a comment", "It creates a variable"], correctIndex: 0, explanation: "Indentation tells Python which statements are part of a block." },
      { id: "basic-syntax-5", question: "Write an `if` statement that prints `Ready` when `score` is at least 50.", interactiveCode: true, initialCode: "score = 75\n\n# Write your if statement below\n", testCode: "", expectedOutput: "Ready", explanation: "Use `if score >= 50:` followed by an indented `print(\"Ready\")`." },
    ] },
  ],
};
