import { type LessonContent } from "@/lessons/types";

export const LISTS_LESSON: LessonContent = {
  slug: "lists",
  title: "Lists",
  subtitle: "Store ordered collections, update them in place, and transform their contents.",
  sections: [
    { kind: "prose", heading: "Why lists matter", body: ["A list stores several values in one ordered collection. Use one when related values belong together and the collection may need to change.", "Lists are mutable, indexed, and allow duplicate values. A list can also contain mixed value types or another list."] },
    { kind: "animation", variant: "list-operations", caption: "A list keeps item order while methods read, add, and remove values" },
    { kind: "syntax", title: "Create a list", code: "items = [value_one, value_two, value_three]\nempty_items = []", description: "Square brackets create a list. Separate its items with commas." },
    { kind: "interactive-code", caption: "LISTS · CREATE AND INSPECT", code: 'scores = [82, 91, 82]\nprofile = ["Ava", 21, True]\nempty = []\n\nprint(scores)\nprint(profile)\nprint(empty)' },
    { kind: "prose", heading: "Indexing", body: ["Every item has a position called an index. Python starts counting at 0, so the first item is at index 0.", "Negative indexes count from the end. `items[-1]` is the last item."] },
    { kind: "syntax", title: "Access one item", code: "first = items[0]\nlast = items[-1]", description: "The index must exist. An out-of-range index raises `IndexError`." },
    { kind: "interactive-code", caption: "INDEXING · POSITIVE AND NEGATIVE", code: 'cities = ["Delhi", "Tokyo", "Lima", "Oslo"]\n\nprint(cities[0])\nprint(cities[2])\nprint(cities[-1])' },
    { kind: "prose", heading: "Slicing", body: ["A slice creates a new list containing part of the original. The start position is included and the end position is excluded.", "Leave out the start or end to slice from an edge. A step of `-1` gives a reversed copy."] },
    { kind: "syntax", title: "Slice a list", code: "items[start:end:step]", description: "`items[1:4]` contains indexes 1, 2, and 3. It does not include index 4." },
    { kind: "interactive-code", caption: "SLICING · EXAMPLE", code: 'numbers = [10, 20, 30, 40, 50, 60]\n\nprint(numbers[1:4])\nprint(numbers[:3])\nprint(numbers[3:])\nprint(numbers[::2])\nprint(numbers[::-1])' },
    { kind: "prose", heading: "Changing and adding items", body: ["Because lists are mutable, assign through an index to replace an existing item. Use `append()` for one item at the end, `extend()` for every item from another iterable, and `insert()` for a chosen position."] },
    { kind: "syntax", title: "Update and add", code: "items[index] = replacement\nitems.append(value)\nitems.extend(values)\nitems.insert(index, value)", description: "These list methods mutate the original list and return `None`." },
    { kind: "interactive-code", caption: "MUTATION · UPDATE AND ADD", code: 'tasks = ["plan", "test"]\ntasks[1] = "build"\ntasks.append("ship")\ntasks.extend(["review", "share"])\ntasks.insert(1, "design")\n\nprint(tasks)' },
    { kind: "prose", heading: "Replacing a slice", body: ["Slice assignment replaces several adjacent items at once. It can also insert items when the slice is empty or delete a range when the replacement is an empty list."] },
    { kind: "syntax", title: "Slice assignment", code: "items[start:end] = replacements\nitems[index:index] = new_items\nitems[start:end] = []", description: "The replacement can contain fewer, equal, or more items than the slice it replaces." },
    { kind: "interactive-code", caption: "SLICE ASSIGNMENT · REPLACE, INSERT, DELETE", code: 'scores = [70, 80, 90, 100]\nscores[1:3] = [88, 95]\nprint(scores)\n\nscores[1:1] = [75]\nprint(scores)\n\nscores[2:4] = []\nprint(scores)' },
    { kind: "prose", heading: "Removing items", body: ["`remove(value)` deletes the first matching value. `pop()` removes and returns the final item, or the item at an index when given one. `clear()` removes every item.", "Use `del items[index]` when you only need to delete by position and do not need the removed value."] },
    { kind: "syntax", title: "Remove items", code: "items.remove(value)\nremoved = items.pop(index)\ndel items[index]\nitems.clear()", description: "`remove()` raises `ValueError` if its value is absent. `pop(index)` raises `IndexError` for an invalid index." },
    { kind: "interactive-code", caption: "REMOVAL · EXAMPLE", code: 'queue = ["Ava", "Noah", "Mia", "Noah"]\nqueue.remove("Noah")\nserved = queue.pop(1)\ndel queue[0]\n\nprint(served)\nprint(queue)' },
    { kind: "prose", heading: "Searching and useful functions", body: ["Use `in` to test membership. `index()` finds the first position of a value and `count()` counts how many times it appears.", "Built-in functions such as `len()`, `min()`, `max()`, and `sum()` inspect numeric lists without changing them."] },
    { kind: "interactive-code", caption: "SEARCH AND FUNCTIONS · EXAMPLE", code: 'numbers = [8, 3, 8, 10]\n\nprint(8 in numbers)\nprint(numbers.index(3))\nprint(numbers.count(8))\nprint(len(numbers))\nprint(min(numbers), max(numbers), sum(numbers))' },
    { kind: "prose", heading: "Sorting and reversing", body: ["`list.sort()` sorts the existing list and `list.reverse()` reverses it in place. `sorted(list)` returns a new sorted list, leaving the original unchanged.", "Do not assign the result of `list.sort()` to a variable. It returns `None` because it modifies the list itself."] },
    { kind: "syntax", title: "Sort and reverse", code: "items.sort()\nitems.sort(reverse=True)\nordered = sorted(items)\nitems.reverse()", description: "Choose `sorted()` when you need to preserve the original order." },
    { kind: "interactive-code", caption: "SORTING · IN PLACE VS NEW LIST", code: 'scores = [88, 72, 95, 81]\nascending_copy = sorted(scores)\n\nprint(scores)\nprint(ascending_copy)\n\nscores.sort(reverse=True)\nprint(scores)' },
    { kind: "prose", heading: "Copying lists", body: ["Assignment does not copy a list. After `backup = items`, both names refer to the same list, so changing either name changes that one shared list.", "Use `.copy()`, `items[:]`, or `list(items)` to make a new outer list. Those are shallow copies. For a flat list, that is usually enough."] },
    { kind: "interactive-code", caption: "COPYING · ALIAS VS NEW LIST", code: 'original = [10, 20, 30]\nalias = original\ncopy = original.copy()\n\nalias.append(40)\ncopy.append(50)\n\nprint(original)\nprint(copy)' },
    { kind: "prose", heading: "Shallow copy", body: ["A shallow copy has its own outer list, but nested lists inside it are still shared. Updating an inner list through the copy also changes that inner list in the original.", "Use a shallow copy for flat data or when shared nested objects are intentional."] },
    { kind: "syntax", title: "Shallow copy", code: "shallow = original.copy()\n# also: original[:] or list(original)", description: "The outer list is new. Nested objects inside it keep their original references." },
    { kind: "interactive-code", caption: "SHALLOW COPY · NESTED LISTS", code: 'original = [[10, 20], [30, 40]]\nshallow = original.copy()\n\nshallow[0][0] = 99\n\nprint(original)\nprint(shallow)' },
    { kind: "prose", heading: "Deep copy", body: ["`copy.deepcopy()` recursively creates new nested objects. Changing an inner list in the deep copy does not change the original.", "Use it when nested data needs to become fully independent. It does more work and is not needed for ordinary flat lists."] },
    { kind: "syntax", title: "Deep copy", code: "import copy\ndeep = copy.deepcopy(original)", description: "A deep copy recreates the outer list and the nested lists inside it." },
    { kind: "interactive-code", caption: "DEEP COPY · NESTED LISTS", code: 'import copy\n\noriginal = [[10, 20], [30, 40]]\ndeep = copy.deepcopy(original)\n\ndeep[0][0] = 99\n\nprint(original)\nprint(deep)' },
    { kind: "prose", heading: "Nested lists", body: ["A nested list is a list that contains other lists. It is useful for rows and columns, grouped values, and simple matrix-shaped data.", "Use one index for the row and another for the item inside that row."] },
    { kind: "syntax", title: "Nested list access", code: "matrix = [[1, 2], [3, 4]]\nvalue = matrix[row_index][column_index]", description: "Each inner list is its own object and can be updated through both indexes." },
    { kind: "interactive-code", caption: "NESTED LISTS · EXAMPLE", code: 'matrix = [[1, 2, 3], [4, 5, 6]]\n\nprint(matrix[1][0])\nmatrix[0][2] = 30\nprint(matrix)' },
    { kind: "prose", heading: "List comprehensions", body: ["A list comprehension creates a new list from an iterable in one expression. It is useful for a simple transformation or filter.", "Use a regular loop when the operation needs several steps or the comprehension becomes hard to read."] },
    { kind: "syntax", title: "List comprehension", code: "new_items = [expression for item in iterable]\nfiltered_items = [expression for item in iterable if condition]", description: "The expression produces each new value. The optional condition keeps matching items only." },
    { kind: "interactive-code", caption: "LIST COMPREHENSIONS · EXAMPLE", code: 'numbers = [1, 2, 3, 4, 5]\nsquares = [number ** 2 for number in numbers]\neven_squares = [number ** 2 for number in numbers if number % 2 == 0]\n\nprint(squares)\nprint(even_squares)' },
    { kind: "prose", heading: "List unpacking", body: ["Unpacking assigns list items to several names at once. The number of target names must match the number of items unless one target uses `*` to collect the remaining values."] },
    { kind: "interactive-code", caption: "UNPACKING · EXAMPLE", code: 'first, second, third = ["red", "green", "blue"]\nhead, *middle, tail = [10, 20, 30, 40]\n\nprint(first, third)\nprint(head, middle, tail)' },
    { kind: "callout", tone: "warn", title: "Common mistakes", body: "- **Using index 1 for the first item**: Python list indexes start at 0.\n- **Forgetting that slice ends are excluded**: `items[1:4]` stops before index 4.\n- **Using `append([\"a\", \"b\"])` when you mean `extend([\"a\", \"b\"])`**: `append()` adds the whole list as one nested item, while `extend()` adds each value.\n- **Assigning `result = items.sort()`**: `sort()` changes the list and returns `None`. Use `sorted(items)` for a new list.\n- **Expecting `backup = items` to copy**: It creates an alias to the same list.\n- **Removing a missing value**: `remove(value)` raises `ValueError` when the value is absent." },
    { kind: "takeaways", items: ["Lists are ordered, mutable collections that can contain duplicates and mixed values.", "Use indexes, slices, and slice assignment to access or reshape list data.", "Use list methods to add, remove, search, sort, reverse, and copy values.", "Assignment aliases a list; shallow copies share nested values, while `copy.deepcopy()` creates independent nested data.", "Nested lists, comprehensions, and unpacking help shape list data for real tasks."] },
    { kind: "quiz", questions: [
      { id: "lists-1", question: "What does `items[-1]` access?", options: ["The last item", "The first item", "A new item", "The list length"], correctIndex: 0, explanation: "Negative index -1 refers to the final item." },
      { id: "lists-2", question: "Which method adds every item from another list?", options: ["`extend()`", "`append()`", "`insert()`", "`copy()`"], correctIndex: 0, explanation: "`extend()` adds each item from another iterable. `append()` adds its argument as one item." },
      { id: "lists-3", question: "Which expression returns a sorted new list without changing `scores`?", options: ["`sorted(scores)`", "`scores.sort()`", "`scores.reverse()`", "`scores.pop()`"], correctIndex: 0, explanation: "`sorted(scores)` returns a new sorted list and preserves the original list." },
      { id: "lists-4", question: "What is true after `second = first` for a list?", options: ["Both names refer to the same list", "second is always empty", "A deep copy is made", "Only second can be changed"], correctIndex: 0, explanation: "Assignment creates another reference to the same list object." },
      { id: "lists-5", question: "Create `tasks = [\"plan\", \"build\"]`, append `\"ship\"`, then print the list.", interactiveCode: true, initialCode: "# Write your code below\n", testCode: "assert tasks == ['plan', 'build', 'ship']", expectedOutput: "['plan', 'build', 'ship']", requiredCodePatterns: ["\\btasks\\s*=\\s*\\[\\s*(['\\\"])plan\\1\\s*,\\s*(['\\\"])build\\2\\s*\\]", "\\btasks\\.append\\s*\\(\\s*(['\\\"])ship\\1\\s*\\)", "\\bprint\\s*\\(\\s*tasks\\s*\\)"], validationMessage: "Create `tasks`, append `ship`, then print the list.", explanation: "`append()` adds one item to the end of the existing list." },
    ] },
  ],
};

export const DATA_STRUCTURES_TOPICS: Record<string, { title: string; slug: string; lessons: LessonContent[] }> = {
  "data-structures": {
    title: "Data Structures",
    slug: "data-structures",
    lessons: [LISTS_LESSON],
  },
};
