import { type LessonContent } from "@/lessons/types";

export const LISTS_LESSON: LessonContent = {
  slug: "lists",
  title: "Lists",
  subtitle: "Store ordered collections, update them in place, and transform their contents.",
  sections: [
    { kind: "prose", heading: "Why lists matter", body: ["A list stores several values in one ordered collection. Use one when related values belong together and the collection may need to change.", "Lists are **mutable, indexed,** and allow **duplicate values.** A list can also contain mixed value types or another list."] },
    { kind: "animation", variant: "list-operations", caption: "A list keeps item order while methods read, add, and remove values" },
    { kind: "syntax", title: "Create a list", code: "items = [value_one, value_two, value_three]\nempty_items = []", description: "Square brackets create a list. Separate its items with commas." },
    { kind: "interactive-code", caption: "LISTS · CREATE AND INSPECT", code: 'scores = [82, 91, 82]\nprofile = ["Ava", 21, True]\nempty = []\n\nprint(scores)\nprint(profile)\nprint(empty)' },
    { kind: "prose", heading: "Indexing", body: ["Every item has a position called an index. Python starts counting at 0, so the first item is at index 0.", "Negative indexes count from the end. `items[-1]` is the last item."] },
    { kind: "syntax", title: "Access one item", code: "first = items[0]\nlast = items[-1]", description: "The index must exist. An out-of-range index raises `IndexError`." },
    { kind: "interactive-code", caption: "INDEXING · POSITIVE AND NEGATIVE", code: 'cities = ["Delhi", "Tokyo", "Lima", "Oslo"]\n\nprint(cities[0])\nprint(cities[2])\nprint(cities[-1])' },
    { kind: "prose", heading: "Slicing", body: ["A slice creates a new list containing part of the original. The start position is included and the end position is excluded.", "Leave out the start or end to slice from an edge. A step of `-1` gives a reversed copy."] },
    { kind: "syntax", title: "Slice a list", code: "items[start:end:step]", description: "`items[1:4]` contains indexes 1, 2, and 3. It does not include index 4." },
    { kind: "interactive-code", caption: "SLICING · EXAMPLE", code: 'numbers = [10, 20, 30, 40, 50, 60]\n\nprint(numbers[1:4])\nprint(numbers[:3])\nprint(numbers[3:])\nprint(numbers[::2])\nprint(numbers[::-1])' },
    { kind: "prose", heading: "Changing and adding items", body: ["Because lists are mutable, assign through an index to replace an existing item. Use `append()` for one item at the end, `extend()` for every item from another iterable, and `insert()` for a chosen position."] },
    { kind: "syntax", title: "Update and add", code: "items[index] = replacement\nitems.append(value)\nitems.extend(values)\nitems.insert(index, value)", description: "These list methods mutate the original list and return `None`." },
    { kind: "interactive-code", caption: "MUTATION · UPDATE AND ADD", code: 'tasks = ["plan", "test"]\ntasks[1] = "build"\ntasks.append("ship")\ntasks.extend(["review", "share"])\ntasks.insert(1, "design")\n\nprint(tasks)' },
    { kind: "prose", heading: "Replacing a slice", body: ["Slice assignment replaces several adjacent items at once. It can also insert items when the slice is empty or delete a range when the replacement is an empty list."] },
    { kind: "syntax", title: "Slice assignment", code: "items[start:end] = replacements\nitems[index:index] = new_items\nitems[start:end] = []", description: "The replacement can contain fewer, equal, or more items than the slice it replaces." },
    { kind: "interactive-code", caption: "SLICE ASSIGNMENT · REPLACE, INSERT, DELETE", code: 'scores = [70, 80, 90, 100]\nscores[1:3] = [88, 95]\nprint(scores)\n\nscores[1:1] = [75]\nprint(scores)\n\nscores[2:4] = []\nprint(scores)' },
    { kind: "prose", heading: "Removing items", body: ["`remove(value)` deletes the first matching value. `pop()` removes and returns the final item, or the item at an index when given one. `clear()` removes every item.", "Use `del items[index]` when you only need to delete by position and do not need the removed value."] },
    { kind: "syntax", title: "Remove items", code: "items.remove(value)\nremoved = items.pop(index)\ndel items[index]\nitems.clear()", description: "`remove()` raises `ValueError` if its value is absent. `pop(index)` raises `IndexError` for an invalid index." },
    { kind: "interactive-code", caption: "REMOVAL · EXAMPLE", code: 'queue = ["Ava", "Noah", "Mia", "Noah"]\nqueue.remove("Noah")\nserved = queue.pop(1)\ndel queue[0]\n\nprint(served)\nprint(queue)' },
    { kind: "prose", heading: "Searching and useful functions", body: ["Use `in` to test membership. `index()` finds the first position of a value and `count()` counts how many times it appears.", "Built-in functions such as `len()`, `min()`, `max()`, and `sum()` inspect numeric lists without changing them."] },
    { kind: "interactive-code", caption: "SEARCH AND FUNCTIONS · EXAMPLE", code: 'numbers = [8, 3, 8, 10]\n\nprint(8 in numbers)\nprint(numbers.index(3))\nprint(numbers.count(8))\nprint(len(numbers))\nprint(min(numbers), max(numbers), sum(numbers))' },
    { kind: "prose", heading: "Sorting and reversing", body: ["`list.sort()` sorts the existing list and `list.reverse()` reverses it in place. `sorted(list)` returns a new sorted list, leaving the original unchanged.", "Do not assign the result of `list.sort()` to a variable. It returns `None` because it modifies the list itself."] },
    { kind: "syntax", title: "Sort and reverse", code: "items.sort()\nitems.sort(reverse=True)\nordered = sorted(items)\nitems.reverse()", description: "Choose `sorted()` when you need to preserve the original order." },
    { kind: "interactive-code", caption: "SORTING · IN PLACE VS NEW LIST", code: 'scores = [88, 72, 95, 81]\nascending_copy = sorted(scores)\n\nprint(scores)\nprint(ascending_copy)\n\nscores.sort(reverse=True)\nprint(scores)' },
    { kind: "prose", heading: "Copying lists", body: ["Assignment does not copy a list. After `backup = items`, both names refer to the same list, so changing either name changes that one shared list.", "Use `.copy()`, `items[:]`, or `list(items)` to make a new outer list. Those are shallow copies. For a flat list, that is usually enough."] },
    { kind: "interactive-code", caption: "COPYING · ALIAS VS NEW LIST", code: 'original = [10, 20, 30]\nalias = original\ncopy = original.copy()\n\nalias.append(40)\ncopy.append(50)\n\nprint(original)\nprint(copy)' },
    { kind: "prose", heading: "Shallow copy", body: ["A shallow copy has its own outer list, but nested lists inside it are still shared. Updating an inner list through the copy also changes that inner list in the original.", "Use a shallow copy for flat data or when shared nested objects are intentional."] },
    { kind: "syntax", title: "Shallow copy", code: "shallow = original.copy()\n# also: original[:] or list(original)", description: "The outer list is new. Nested objects inside it keep their original references." },
    { kind: "interactive-code", caption: "SHALLOW COPY · NESTED LISTS", code: 'original = [[10, 20], [30, 40]]\nshallow = original.copy()\n\nshallow[0][0] = 99\n\nprint(original)\nprint(shallow)' },
    { kind: "prose", heading: "Deep copy", body: ["`copy.deepcopy()` recursively creates new nested objects. Changing an inner list in the deep copy does not change the original.", "Use it when nested data needs to become fully independent. It does more work and is not needed for ordinary flat lists."] },
    { kind: "syntax", title: "Deep copy", code: "import copy\ndeep = copy.deepcopy(original)", description: "A deep copy recreates the outer list and the nested lists inside it." },
    { kind: "interactive-code", caption: "DEEP COPY · NESTED LISTS", code: 'import copy\n\noriginal = [[10, 20], [30, 40]]\ndeep = copy.deepcopy(original)\n\ndeep[0][0] = 99\n\nprint(original)\nprint(deep)' },
    { kind: "prose", heading: "Nested lists", body: ["A nested list is a list that contains other lists. It is useful for rows and columns, grouped values, and simple matrix-shaped data.", "Use one index for the row and another for the item inside that row."] },
    { kind: "syntax", title: "Nested list access", code: "matrix = [[1, 2], [3, 4]]\nvalue = matrix[row_index][column_index]", description: "Each inner list is its own object and can be updated through both indexes." },
    { kind: "interactive-code", caption: "NESTED LISTS · EXAMPLE", code: 'matrix = [[1, 2, 3], [4, 5, 6]]\n\nprint(matrix[1][0])\nmatrix[0][2] = 30\nprint(matrix)' },
    { kind: "prose", heading: "List comprehensions", body: ["A list comprehension creates a new list from an iterable in one expression. It is useful for a simple transformation or filter.", "Use a regular loop when the operation needs several steps or the comprehension becomes hard to read."] },
    { kind: "syntax", title: "List comprehension", code: "new_items = [expression for item in iterable]\nfiltered_items = [expression for item in iterable if condition]", description: "The expression produces each new value. The optional condition keeps matching items only." },
    { kind: "interactive-code", caption: "LIST COMPREHENSIONS · EXAMPLE", code: 'numbers = [1, 2, 3, 4, 5]\nsquares = [number ** 2 for number in numbers]\neven_squares = [number ** 2 for number in numbers if number % 2 == 0]\n\nprint(squares)\nprint(even_squares)' },
    { kind: "prose", heading: "List unpacking", body: ["Unpacking assigns list items to several names at once. The number of target names must match the number of items unless one target uses `*` to collect the remaining values."] },
    { kind: "interactive-code", caption: "UNPACKING · EXAMPLE", code: 'first, second, third = ["red", "green", "blue"]\nhead, *middle, tail = [10, 20, 30, 40]\n\nprint(first, third)\nprint(head, middle, tail)' },
    { kind: "callout", tone: "warn", title: "Common mistakes", body: "- **Using index 1 for the first item**: Python list indexes start at 0.\n- **Forgetting that slice ends are excluded**: `items[1:4]` stops before index 4.\n- **Using `append([\"a\", \"b\"])` when you mean `extend([\"a\", \"b\"])`**: `append()` adds the whole list as one nested item, while `extend()` adds each value.\n- **Assigning `result = items.sort()`**: `sort()` changes the list and returns `None`. Use `sorted(items)` for a new list.\n- **Expecting `backup = items` to copy**: It creates an alias to the same list.\n- **Removing a missing value**: `remove(value)` raises `ValueError` when the value is absent." },
    { kind: "takeaways", items: ["Lists are ordered, mutable collections that can contain duplicates and mixed values.", "Use indexes, slices, and slice assignment to access or reshape list data.", "Use list methods to add, remove, search, sort, reverse, and copy values.", "Assignment aliases a list; shallow copies share nested values, while `copy.deepcopy()` creates independent nested data.", "Nested lists, comprehensions, and unpacking help shape list data for real tasks."] },
    {
      kind: "quiz", questions: [
        { id: "lists-1", question: "What does `items[-1]` access?", options: ["The last item", "The first item", "A new item", "The list length"], correctIndex: 0, explanation: "Negative index -1 refers to the final item." },
        { id: "lists-2", question: "Which method adds every item from another list?", options: ["`extend()`", "`append()`", "`insert()`", "`copy()`"], correctIndex: 0, explanation: "`extend()` adds each item from another iterable. `append()` adds its argument as one item." },
        { id: "lists-3", question: "Which expression returns a sorted new list without changing `scores`?", options: ["`sorted(scores)`", "`scores.sort()`", "`scores.reverse()`", "`scores.pop()`"], correctIndex: 0, explanation: "`sorted(scores)` returns a new sorted list and preserves the original list." },
        { id: "lists-4", question: "What is true after `second = first` for a list?", options: ["Both names refer to the same list", "second is always empty", "A deep copy is made", "Only second can be changed"], correctIndex: 0, explanation: "Assignment creates another reference to the same list object." },
        { id: "lists-5", question: "Create `tasks = [\"plan\", \"build\"]`, append `\"ship\"`, then print the list.", interactiveCode: true, initialCode: "# Write your code below\n", testCode: "assert tasks == ['plan', 'build', 'ship']", expectedOutput: "['plan', 'build', 'ship']", requiredCodePatterns: ["\\btasks\\s*=\\s*\\[\\s*(['\\\"])plan\\1\\s*,\\s*(['\\\"])build\\2\\s*\\]", "\\btasks\\.append\\s*\\(\\s*(['\\\"])ship\\1\\s*\\)", "\\bprint\\s*\\(\\s*tasks\\s*\\)"], validationMessage: "Create `tasks`, append `ship`, then print the list.", explanation: "`append()` adds one item to the end of the existing list." },
      ]
    },
  ],
};

export const TUPLES_LESSON: LessonContent = {
  slug: "tuples",
  title: "Tuples",
  subtitle: "Group ordered values that should stay in the same shape.",
  sections: [
    { kind: "prose", heading: "Why tuples matter", body: ["A tuple stores ordered values like a list, but its item positions cannot be changed after creation. Use a tuple when the values form a stable record, such as coordinates, an RGB color, or a date.", "Tuples allow duplicate and mixed values. Their immutability communicates that the collection's structure should stay fixed."] },
    { kind: "animation", variant: "tuple-operations", caption: "A tuple preserves order, protects its positions, and can be unpacked into named values" },
    { kind: "syntax", title: "Create a tuple", code: "items = (value_one, value_two, value_three)\nempty_items = ()\nsingle_item = (value,)", description: "Parentheses make the structure clear. A one-item tuple needs a trailing comma." },
    { kind: "interactive-code", caption: "TUPLES · CREATE AND INSPECT", code: 'coordinates = (12, 18)\nprofile = ("Ava", 21, True)\npacked = "red", "green", "blue"\nletters = tuple("ABC")\n\nprint(coordinates)\nprint(profile)\nprint(packed)\nprint(letters)' },
    { kind: "prose", heading: "Single-item tuples", body: ["The **comma**, not the **parentheses**, tells Python that a value belongs in a one-item tuple. Without the comma, parentheses only group the expression."] },
    { kind: "interactive-code", caption: "SINGLE ITEM · THE COMMA MATTERS", code: 'not_a_tuple = ("Python")\na_tuple = ("Python",)\n\nprint(type(not_a_tuple))\nprint(type(a_tuple))' },
    { kind: "prose", heading: "Indexing and slicing", body: ["Tuple indexes work like list indexes. Python starts at 0, and negative indexes count from the end.", "A slice returns a new tuple. The start is included, the end is excluded, and an optional step controls the interval."] },
    { kind: "syntax", title: "Read tuple values", code: "first = items[0]\nlast = items[-1]\nportion = items[start:end:step]", description: "Reading and slicing are allowed because they do not modify the original tuple." },
    { kind: "interactive-code", caption: "INDEXING AND SLICING · EXAMPLE", code: 'months = ("Jan", "Feb", "Mar", "Apr", "May", "Jun")\n\nprint(months[0])\nprint(months[-1])\nprint(months[1:4])\nprint(months[::2])\nprint(months[::-1])' },
    { kind: "prose", heading: "Tuple immutability", body: ["You cannot assign to, append to, or remove an item from a tuple. To represent an updated record, construct a new tuple and assign it to the variable.", "This does not alter the old tuple. The variable is simply given a reference to the new tuple."] },
    { kind: "syntax", title: "Create an updated tuple", code: "items = items[:index] + (replacement,) + items[index + 1:]", description: "This combines slices with a one-item tuple to create a replacement value at one position." },
    { kind: "interactive-code", caption: "IMMUTABILITY · CREATE A REPLACEMENT", code: 'scores = (70, 80, 90)\nupdated_scores = scores[:1] + (88,) + scores[2:]\n\nprint(scores)\nprint(updated_scores)' },
    { kind: "prose", heading: "Tuples can contain mutable values", body: ["A tuple protects the references stored at its positions, but it does not make a list inside it immutable. You cannot replace the inner list, yet you can modify that list itself."] },
    { kind: "interactive-code", caption: "MUTABLE ITEM INSIDE A TUPLE", code: 'record = ([10, 20], "Python")\nrecord[0][1] = 99\n\nprint(record)' },
    { kind: "prose", heading: "Tuple methods and useful functions", body: ["Tuples provide `count()` to count matches and `index()` to find the first matching position. They also work with `len()`, `min()`, `max()`, and `sum()` when the values support those operations.", "`sorted()` accepts a tuple but returns a list, because sorting produces a mutable new collection."] },
    { kind: "interactive-code", caption: "METHODS AND FUNCTIONS · EXAMPLE", code: 'scores = (8, 3, 8, 10)\n\nprint(scores.count(8))\nprint(scores.index(3))\nprint(len(scores))\nprint(min(scores), max(scores), sum(scores))\nprint(sorted(scores))\nprint(type(sorted(scores)))' },
    { kind: "prose", heading: "Tuple operations", body: ["Use `+` to join tuples, `*` to repeat them, and `in` to test membership. Each operation produces a result without changing either original tuple."] },
    { kind: "syntax", title: "Combine and test tuples", code: "combined = first + second\nrepeated = items * 2\nexists = value in items", description: "Concatenation and repetition create new tuples." },
    { kind: "interactive-code", caption: "OPERATIONS · COMBINE, REPEAT, CHECK", code: 'primary = ("red", "blue")\nsecondary = ("green",)\n\nprint(primary + secondary)\nprint(secondary * 3)\nprint("blue" in primary)' },
    { kind: "prose", heading: "Packing and unpacking", body: ["Packing stores comma-separated values in one tuple. Unpacking assigns a tuple's values to separate variables.", "The target count must match the value count unless a starred target collects the remaining values. The starred target becomes a list."] },
    { kind: "syntax", title: "Pack and unpack values", code: "record = name, age, course\nname, age, course = record\nfirst, *middle, last = values", description: "Parentheses are optional while packing, but they usually improve readability." },
    { kind: "interactive-code", caption: "PACKING AND UNPACKING · EXAMPLE", code: 'student = "Ava", 21, "Python"\nname, age, course = student\nfirst, *middle, last = (10, 20, 30, 40, 50)\n\nprint(name, age, course)\nprint(first, middle, last)\nprint(type(middle))' },
    { kind: "prose", heading: "Named tuples", body: ["A named tuple is an immutable tuple with readable field names. It is useful when values always appear in the same positions but an index such as student[0] would be unclear.", "Create one with collections.namedtuple, then access each field by name or by index."] },
    { kind: "interactive-code", caption: "NAMED TUPLE · READABLE RECORD", code: 'from collections import namedtuple\n\nStudent = namedtuple("Student", ["name", "age"])\nstudent = Student("Ava", 21)\n\nprint(student.name)\nprint(student[1])' },
    { kind: "table", caption: "List or tuple?", headers: ["Choose", "When it fits", "Key property"], rows: [["List", "The collection will change", "Mutable, uses []"], ["Tuple", "The record should stay fixed", "Immutable, uses ()"], ["Tuple", "A function returns several related values", "Can be unpacked cleanly"]] },
    { kind: "prose", heading: "Converting between lists and tuples", body: ["Use tuple(values) to create a tuple from an iterable. Use list(items) when you need a mutable copy that can be updated with list methods."] },
    { kind: "interactive-code", caption: "CONVERT · LIST AND TUPLE", code: 'names = ["Ava", "Noah"]\nfixed_names = tuple(names)\neditable_names = list(fixed_names)\neditable_names.append("Mia")\n\nprint(fixed_names)\nprint(editable_names)' },
    { kind: "callout", tone: "warn", title: "Common mistakes", body: "- **Forgetting the comma in a one-item tuple**: (42) is an integer, while (42,) is a tuple.\n- **Trying to update a tuple position**: items[0] = value raises TypeError. Create a new tuple instead.\n- **Assuming every nested value is immutable**: a list stored inside a tuple can still be changed.\n- **Expecting sorted(tuple) to return a tuple**: it returns a list.\n- **Unpacking into the wrong number of names**: use a starred target when one name should receive the remaining values." },
    { kind: "takeaways", items: ["Tuples are ordered collections whose positions cannot be changed after creation.", "Use a trailing comma for a one-item tuple.", "Indexing and slicing read tuple data, while concatenation and repetition create new tuples.", "Packing and unpacking make it easy to move between a fixed record and named variables.", "Use tuples for stable records and lists when the collection needs in-place changes."] },
    {
      kind: "quiz", questions: [
        { id: "tuples-1", question: "Which expression creates a one-item tuple containing 42?", options: ["(42,)", "(42)", "[42]", "{42}"], correctIndex: 0, explanation: "A trailing comma is required for a one-item tuple." },
        { id: "tuples-2", question: "What happens when code tries point[0] = 10 for a tuple?", options: ["It raises TypeError", "It updates the first value", "It appends 10", "It converts the tuple to a list"], correctIndex: 0, explanation: "Tuple positions are immutable and cannot be reassigned." },
        { id: "tuples-3", question: "What type does sorted((3, 1, 2)) return?", options: ["A list", "A tuple", "A set", "An integer"], correctIndex: 0, explanation: "sorted() creates and returns a new list." },
        { id: "tuples-4", question: "After first, *middle, last = (10, 20, 30, 40), what is middle?", options: ["[20, 30]", "(20, 30)", "20", "[10, 40]"], correctIndex: 0, explanation: "A starred unpacking target collects the remaining values into a list." },
        { id: "tuples-5", question: "Create coordinates = (12, 18), unpack it into x and y, then print their sum.", interactiveCode: true, initialCode: "# Write your code below\n", testCode: "assert coordinates == (12, 18)\nassert x == 12\nassert y == 18", expectedOutput: "30", requiredCodePatterns: ["\\bcoordinates\\s*=\\s*\\(\\s*12\\s*,\\s*18\\s*\\)", "\\bx\\s*,\\s*y\\s*=\\s*coordinates\\b", "\\bprint\\s*\\(\\s*x\\s*\\+\\s*y\\s*\\)"], validationMessage: "Create the tuple, unpack it into x and y, then print x + y.", explanation: "Unpacking gives each tuple position its own variable." },
      ]
    },
  ],
};

export const SETS_LESSON: LessonContent = {
  slug: "sets",
  title: "Sets",
  subtitle: "Keep unique values, test membership quickly, and compare groups of data.",
  sections: [
    { kind: "prose", heading: "Why sets matter", body: ["A set stores unique values. It is a strong fit for removing duplicates, checking whether something exists, and comparing groups such as enrolled students and attendees.", "Sets are **mutable and unordered**. Their values have **no fixed indexes**, and displayed order can differ between runs."] },
    { kind: "animation", variant: "set-operations", caption: "Sets automatically remove duplicates and make group comparisons explicit" },
    { kind: "syntax", title: "Create a set", code: "items = {value_one, value_two, value_three}\nempty_items = set()", description: "Curly braces create a non-empty set. Use set() for an empty set because {} creates a dictionary." },
    { kind: "interactive-code", caption: "SETS · CREATE AND DEDUPLICATE", code: 'numbers = {10, 20, 10, 30, 20}\nempty = set()\nfrom_list = set([1, 2, 2, 3])\n\nprint(numbers)\nprint(empty)\nprint(from_list)' },
    { kind: "prose", heading: "Unique and hashable values", body: ["A set automatically keeps one copy of each equal value. Its elements must be hashable, which means they cannot change in a way that would break lookup.", "Numbers, strings, booleans, and tuples containing only immutable values can belong to a set. Lists, dictionaries, and ordinary sets cannot."] },
    { kind: "interactive-code", caption: "HASHABLE VALUES · VALID SET MEMBERS", code: 'valid = {10, "Python", (1, 2), True}\n\nprint(valid)\nprint((1, 2) in valid)' },
    { kind: "prose", heading: "No indexing or slicing", body: ["Sets do not preserve positions, so indexing and slicing are not available. Loop over a set to visit its values, and use in or not in to check membership.", "Membership checks are usually faster with a set than a list when the collection is large."] },
    { kind: "interactive-code", caption: "MEMBERSHIP · CHECK VALUES", code: 'languages = {"Python", "Java", "C++"}\n\nprint("Python" in languages)\nprint("Rust" not in languages)\n\nfor language in languages:\n    print(language)' },
    { kind: "prose", heading: "Adding values", body: ["`add()` adds one value and `update()` adds values from an iterable. If a value already exists, the set remains unchanged because duplicates are not stored."] },
    { kind: "syntax", title: "Add set values", code: "items.add(value)\nitems.update(iterable)", description: "Both methods change the existing set." },
    { kind: "interactive-code", caption: "MUTATION · ADD AND UPDATE", code: 'skills = {"Python", "SQL"}\nskills.add("Git")\nskills.update(["SQL", "Docker"])\n\nprint(sorted(skills))' },
    { kind: "prose", heading: "Removing values", body: ["remove() and discard() both remove a specified value. remove() raises KeyError when the value is missing, while discard() safely does nothing.", "pop() removes and returns an arbitrary value because a set is unordered. clear() empties the set."] },
    { kind: "syntax", title: "Remove set values", code: "items.remove(value)\nitems.discard(value)\nremoved = items.pop()\nitems.clear()", description: "Use discard() when an absent value should not be an error." },
    { kind: "interactive-code", caption: "MUTATION · REMOVE AND DISCARD", code: 'attendees = {"Ava", "Noah", "Mia"}\nattendees.remove("Noah")\nattendees.discard("Unknown")\n\nprint(sorted(attendees))' },
    { kind: "prose", heading: "Set operations", body: ["Set operations compare or combine groups without writing a loop. Union keeps all values, intersection keeps shared values, difference keeps values only in the first set, and symmetric difference keeps values not shared by both.", "The operator forms and method forms produce new sets, leaving the original sets unchanged."] },
    { kind: "table", caption: "Core set operations", headers: ["Operation", "Operator", "Method", "Result"], rows: [["Union", "|", "a.union(b)", "All unique values"], ["Intersection", "&", "a.intersection(b)", "Shared values"], ["Difference", "-", "a.difference(b)", "Values in a but not b"], ["Symmetric difference", "^", "a.symmetric_difference(b)", "Values not shared"]] },
    { kind: "interactive-code", caption: "SET OPERATIONS · COMPARE GROUPS", code: 'morning = {"Ava", "Noah", "Mia"}\nafternoon = {"Mia", "Leo", "Noah"}\n\nprint(sorted(morning | afternoon))\nprint(sorted(morning & afternoon))\nprint(sorted(morning - afternoon))\nprint(sorted(morning ^ afternoon))' },
    { kind: "prose", heading: "Subset, superset, and disjoint sets", body: ["A subset has all of its values inside another set. A superset contains all values from another set. Disjoint sets have no values in common.", "Use the methods for readable checks or <= and >= for subset and superset comparisons."] },
    { kind: "interactive-code", caption: "RELATIONSHIPS · SUBSET, SUPERSET, DISJOINT", code: 'core = {"Python", "SQL"}\nall_skills = {"Python", "SQL", "Git"}\nother = {"Docker"}\n\nprint(core.issubset(all_skills))\nprint(all_skills.issuperset(core))\nprint(core.isdisjoint(other))\nprint(core <= all_skills)' },
    { kind: "prose", heading: "Updating with operations", body: ["Methods ending in _update change the original set instead of returning a new one. update() performs a union update, while intersection_update(), difference_update(), and symmetric_difference_update() modify the set for their matching operations."] },
    { kind: "interactive-code", caption: "UPDATE METHODS · CHANGE THE ORIGINAL", code: 'available = {"Python", "SQL", "Git"}\nrequired = {"SQL", "Docker"}\n\navailable.intersection_update(required)\nprint(available)\n\navailable.symmetric_difference_update({"SQL", "Docker"})\nprint(available)' },
    { kind: "prose", heading: "Copying sets", body: ["Assignment creates another name for the same set. Use `copy()` or `set(existing_set)` to create a separate set before changing it."] },
    { kind: "interactive-code", caption: "COPYING · ALIAS VS NEW SET", code: 'original = {"Python", "SQL"}\nalias = original\ncopy = original.copy()\n\nalias.add("Git")\ncopy.add("Docker")\n\nprint(sorted(original))\nprint(sorted(copy))' },
    { kind: "prose", heading: "Frozen sets", body: ["`frozenset` is the immutable form of a set. It supports read-only operations such as **union and intersection** but cannot add or remove values.", "Because a frozenset is hashable, it can be used as a dictionary key or as an element in another set."] },
    { kind: "syntax", title: "Create a frozenset", code: "fixed_items = frozenset(iterable)", description: "Create a frozenset when the unique group itself must not change." },
    { kind: "interactive-code", caption: "FROZENSET · IMMUTABLE UNIQUE VALUES", code: 'roles = frozenset(["reader", "editor", "reader"])\npermissions = frozenset(["reader", "commenter"])\n\nprint(roles)\nprint(roles & permissions)\nprint(type(roles))' },
    { kind: "prose", heading: "Set comprehensions", body: ["A set comprehension creates a set from an iterable in one expression. Like a list comprehension, it can transform values and apply a filter, but duplicate results are automatically removed."] },
    { kind: "syntax", title: "Set comprehension", code: "new_items = {expression for item in iterable}\nfiltered_items = {expression for item in iterable if condition}", description: "Use curly braces and remember that the result is unordered and unique." },
    { kind: "interactive-code", caption: "SET COMPREHENSIONS · TRANSFORM AND FILTER", code: 'numbers = [1, 2, 2, 3, 4, 4]\nsquares = {number * number for number in numbers}\neven_numbers = {number for number in numbers if number % 2 == 0}\n\nprint(sorted(squares))\nprint(sorted(even_numbers))' },
    { kind: "prose", heading: "Converting collections", body: ["`set(iterable)` removes duplicate values from a list, tuple, or string. Converting a set back to a **list** or **tuple** is possible, but do not rely on a particular order after the conversion."] },
    { kind: "interactive-code", caption: "CONVERT · REMOVE DUPLICATES", code: 'numbers = [10, 20, 10, 30, 20]\nunique_numbers = set(numbers)\n\nprint(sorted(unique_numbers))\nprint(list(unique_numbers))\nprint(set("banana"))' },
    { kind: "table", caption: "Choose the right collection", headers: ["Collection", "Order", "Duplicates", "Mutable"], rows: [["List", "Preserved", "Allowed", "Yes"], ["Tuple", "Preserved", "Allowed", "No"], ["Set", "No fixed order", "Removed", "Yes"], ["Frozenset", "No fixed order", "Removed", "No"]] },
    { kind: "callout", tone: "warn", title: "Common mistakes", body: "- **Using {} for an empty set**: it creates an empty dictionary. Use set().\n- **Trying to index a set**: sets have no positions, so items[0] raises TypeError.\n- **Expecting a stable display order**: sort a set before printing when order matters for a demonstration.\n- **Using remove() for optional values**: discard() is safer when the value might be absent.\n- **Putting a list inside a set**: lists are mutable and therefore unhashable." },
    { kind: "takeaways", items: ["Sets keep unique, hashable values and do not provide fixed indexes.", "Use sets for deduplication and fast membership checks.", "add() and update() change a set, while remove() and discard() differ when a value is absent.", "Union, intersection, difference, and symmetric difference compare groups clearly.", "Use frozenset for immutable unique groups and set comprehensions for unique transformed results."] },
    {
      kind: "quiz", questions: [
        { id: "sets-1", question: "Which expression creates an empty set?", options: ["set()", "{}", "[]", "()"], correctIndex: 0, explanation: "set() creates an empty set. {} creates an empty dictionary." },
        { id: "sets-2", question: "Which value cannot be stored directly in a set?", options: ["[1, 2]", "(1, 2)", "Python", "42"], correctIndex: 0, explanation: "Lists are mutable and unhashable, so they cannot be set elements." },
        { id: "sets-3", question: "Which operation keeps only values shared by both sets?", options: ["Intersection", "Union", "Difference", "Symmetric difference"], correctIndex: 0, explanation: "Intersection uses & or intersection() to keep common values." },
        { id: "sets-4", question: "What does discard(value) do when value is not in a set?", options: ["Nothing and does not raise an error", "Raises KeyError", "Adds the value", "Clears the set"], correctIndex: 0, explanation: "discard() safely leaves the set unchanged when the value is absent." },
        { id: "sets-5", question: "Create skills = {Python, SQL}, add Git, then print sorted(skills).", interactiveCode: true, initialCode: "# Write your code below\n", testCode: "assert skills == {'Python', 'SQL', 'Git'}", expectedOutput: "['Git', 'Python', 'SQL']", requiredCodePatterns: ["\\bskills\\s*=\\s*\\{", "\\bskills\\.add\\s*\\(\\s*(['\\\"])Git\\1\\s*\\)", "\\bprint\\s*\\(\\s*sorted\\s*\\(\\s*skills\\s*\\)\\s*\\)"], validationMessage: "Create the set, add Git, then print sorted(skills).", explanation: "Sets are unordered, so sorted(skills) gives a stable printed list." },
      ]
    },
  ],
};

export const DICTIONARIES_LESSON: LessonContent = {
  slug: "dictionaries",
  title: "Dictionaries",
  subtitle: "Model named information with flexible key-value pairs.",
  sections: [
    { kind: "prose", heading: "Why dictionaries matter", body: ["A dictionary maps each unique key to a value. It is useful when position is less meaningful than a label, such as a student profile, product details, or an API response.", "Dictionaries are mutable and preserve insertion order in modern Python. `Keys` must be **unique and hashable**, while `values` can be **any type** and **may repeat**."] },
    { kind: "animation", variant: "dictionary-operations", caption: "A dictionary connects stable keys to values that can be read, changed, and merged" },
    { kind: "syntax", title: "Create a dictionary", code: "record = {\n    key_one: value_one,\n    key_two: value_two,\n}\nempty_record = {}", description: "Each key and value are separated by a colon. Pairs are separated by commas." },
    { kind: "interactive-code", caption: "DICTIONARIES · CREATE RECORDS", code: 'student = {"name": "Ava", "age": 21, "active": True}\nfrom_constructor = dict(course="Python", level="Beginner")\ncoordinates = {(10, 20): "start"}\n\nprint(student)\nprint(from_constructor)\nprint(coordinates)' },
    { kind: "prose", heading: "Keys and values", body: ["Keys identify values, so they must be unique and hashable. Strings, numbers, and tuples containing immutable values are valid keys. Lists, dictionaries, and sets are not valid keys.", "When a dictionary literal repeats a key, the final value replaces the earlier one. Values do not need to be unique."] },
    { kind: "interactive-code", caption: "UNIQUE KEYS · LAST VALUE WINS", code: 'profile = {"name": "Ava", "name": "Mia", "score": 90}\nvalid_keys = {1: "one", (10, 20): "point"}\n\nprint(profile)\nprint(valid_keys)' },
    { kind: "prose", heading: "Accessing values", body: ["Use square brackets to access a known key. A missing key raises `KeyError`. Use `get()` when a key may be missing and you want `None` or a **fallback value** instead."] },
    { kind: "syntax", title: "Read a dictionary value", code: "value = record[key]\nsafe_value = record.get(key, default_value)", description: "Bracket access is direct. `get()` is the **safer choice for optional data**." },
    { kind: "interactive-code", caption: "ACCESS · DIRECT AND SAFE", code: 'student = {"name": "Ava", "age": 21}\n\nprint(student["name"])\nprint(student.get("score"))\nprint(student.get("score", "Not available"))' },
    { kind: "prose", heading: "Updating and adding values", body: ["Assigning to an existing key replaces its value. Assigning to a new key adds a new key-value pair. `update()` can apply several changes from another dictionary at once."] },
    { kind: "syntax", title: "Update a dictionary", code: "record[key] = new_value\nrecord.update({key: value})", description: "Both forms **change the existing dictionary**." },
    { kind: "interactive-code", caption: "MUTATION · UPDATE AND ADD", code: 'student = {"name": "Ava", "age": 21}\nstudent["age"] = 22\nstudent["course"] = "Python"\nstudent.update({"active": True, "city": "Chicago"})\n\nprint(student)' },
    { kind: "prose", heading: "Views and helper methods", body: ["`keys()`, `values()`, and `items()` return live views of a dictionary. `items()` is especially useful for working with each key-value pair together.", "`setdefault()` returns a value when a key exists or adds that key with a default when it does not. `dict.fromkeys()` creates a new dictionary from a sequence of keys."] },
    { kind: "interactive-code", caption: "VIEWS · DEFAULTS · NEW KEYS", code: 'progress = {"Python": 4, "SQL": 2}\n\nprint(list(progress.keys()))\nprint(list(progress.values()))\nprint(list(progress.items()))\nprint(progress.setdefault("Git", 0))\nprint(progress)\nprint(dict.fromkeys(["Ava", "Noah"], 0))' },
    { kind: "prose", heading: "Removing dictionary items", body: ["`pop(key)` removes a key and returns its value. `popitem()` removes and returns the last inserted key-value pair. `del` removes a chosen key, and `clear()` removes every pair."] },
    { kind: "syntax", title: "Remove dictionary values", code: "removed = record.pop(key)\nlast_pair = record.popitem()\ndel record[key]\nrecord.clear()", description: "`pop()` and `del` raise `KeyError` if the requested key does not exist." },
    { kind: "interactive-code", caption: "MUTATION · REMOVE PAIRS", code: 'student = {"name": "Ava", "age": 21, "course": "Python"}\nremoved_age = student.pop("age")\ndel student["course"]\n\nprint(removed_age)\nprint(student)' },
    { kind: "prose", heading: "Looping and key membership", body: ["Looping directly over a dictionary yields its keys. Use `values()` for values and `items()` to **unpack each key-value pair**.", "The `in` operator checks `keys`, not `values`. Use `value in record.values()` when you specifically need to search the values."] },
    { kind: "interactive-code", caption: "LOOPING · KEYS, VALUES, PAIRS", code: 'student = {"name": "Ava", "age": 21, "course": "Python"}\n\nprint("name" in student)\nprint("Ava" in student)\n\nfor key, value in student.items():\n    print(key, value)' },
    { kind: "prose", heading: "Nested dictionaries", body: ["A nested dictionary stores dictionaries inside another dictionary. It is a common shape for grouped records such as users, products, and API data.", "Access an inner value by using one key at each level."] },
    { kind: "syntax", title: "Read nested data", code: "value = records[outer_key][inner_key]", description: "Each bracket moves one level deeper into the nested structure." },
    { kind: "interactive-code", caption: "NESTED DICTIONARIES · EXAMPLE", code: 'students = {\n    "ava": {"name": "Ava", "age": 21},\n    "noah": {"name": "Noah", "age": 20},\n}\n\nprint(students["ava"]["name"])\nstudents["noah"]["age"] = 21\nprint(students["noah"])' },
    { kind: "prose", heading: "Dictionary comprehensions", body: ["A dictionary comprehension creates key-value pairs from an iterable in one expression. Add a condition to keep only selected pairs."] },
    { kind: "syntax", title: "Dictionary comprehension", code: "new_record = {key_expression: value_expression for item in iterable}\nfiltered_record = {key: value for key, value in pairs if condition}", description: "The expression before the colon produces the key. The expression after it produces the value." },
    { kind: "interactive-code", caption: "DICTIONARY COMPREHENSIONS · EXAMPLE", code: 'numbers = [1, 2, 3, 4, 5, 6]\nsquares = {number: number * number for number in numbers}\neven_squares = {number: number * number for number in numbers if number % 2 == 0}\n\nprint(squares)\nprint(even_squares)' },
    { kind: "prose", heading: "Merging dictionaries", body: ["`update()` merges another dictionary into the original. The `|` operator returns a new merged dictionary. When both dictionaries have the same key, the value from the second dictionary wins."] },
    { kind: "interactive-code", caption: "MERGING · ORIGINAL OR NEW", code: 'profile = {"name": "Ava", "age": 21}\nextra = {"age": 22, "course": "Python"}\n\nmerged = profile | extra\nprofile.update(extra)\n\nprint(merged)\nprint(profile)' },
    { kind: "prose", heading: "Copying dictionaries", body: ["**Assignment** creates another name for the same dictionary. `copy()` and `dict(existing_record)` create a **new outer dictionary**, which is a **shallow copy**. Nested objects inside it are **still shared**.", "Use `copy.deepcopy()` from Python's `copy` module when nested dictionaries, lists, or sets must be independent too. A deep copy duplicates the outer dictionary and the nested mutable objects it contains."] },
    { kind: "syntax", title: "Choose a copy type", code: "alias = original\nshallow = original.copy()\nfrom copy import deepcopy\ndeep = deepcopy(original)", description: "Assignment shares the original. A shallow copy duplicates only the outer dictionary. deepcopy() recursively duplicates nested mutable values." },
    { kind: "interactive-code", caption: "COPYING · ALIAS VS NEW DICTIONARY", code: 'original = {"name": "Ava", "age": 21}\nalias = original\ncopy = original.copy()\n\nalias["age"] = 22\ncopy["city"] = "Chicago"\n\nprint(original)\nprint(copy)' },
    { kind: "interactive-code", caption: "COPYING · SHALLOW VS DEEP", code: 'from copy import deepcopy\n\noriginal = {"student": {"name": "Ava", "skills": ["Python"]}}\nshallow = original.copy()\ndeep = deepcopy(original)\n\noriginal["student"]["skills"].append("SQL")\n\nprint(shallow["student"]["skills"])\nprint(deep["student"]["skills"])' },
    { kind: "table", caption: "List or dictionary?", headers: ["Choose", "Access values by", "Best fit"], rows: [["List", "Position or index", "An ordered sequence"], ["Dictionary", "Named key", "A labeled record"], ["Dictionary", "Tuple key", "A coordinate or composite identifier"]] },
    { kind: "callout", tone: "warn", title: "Common mistakes", body: "- **Using a list as a dictionary key**: lists are mutable and unhashable.\n- **Expecting duplicate keys to remain**: the last value for a repeated key replaces prior values.\n- **Using brackets for an optional key**: record[key] raises KeyError when missing. Use get() with a default.\n- **Assuming in searches values**: key in record checks keys only.\n- **Confusing a shallow copy with a fully independent nested record**: copy() shares nested lists and dictionaries. Use deepcopy() when nested values must be independent." },
    { kind: "takeaways", items: ["Dictionaries map unique, hashable keys to values of any type.", "Use bracket access for required keys and get() with a fallback for optional keys.", "Assignment updates or adds a key, and update() changes several pairs at once.", "items() supports readable key-value loops, while nested dictionaries model structured records.", "Comprehensions, merging, shallow copies, and deep copies help build and reshape dictionaries safely."] },
    {
      kind: "quiz", questions: [
        { id: "dictionaries-1", question: 'What does record.get("missing", 0) return when missing is absent?', options: ["0", "KeyError", "An empty dictionary", "The last value"], correctIndex: 0, explanation: "get() returns its provided fallback when the key is absent." },
        { id: "dictionaries-2", question: "What does key in record check for a dictionary?", options: ["Keys", "Values", "Both keys and values", "Only integer indexes"], correctIndex: 0, explanation: "Membership on a dictionary checks its keys." },
        { id: "dictionaries-3", question: "When a merge has the same key in both dictionaries, which value wins?", options: ["The value from the second dictionary", "The value from the first dictionary", "Both values are kept", "Python raises KeyError"], correctIndex: 0, explanation: "Later values replace earlier values for matching keys." },
        { id: "dictionaries-4", question: "Which loop gives both a key and its value?", options: ["for key, value in record.items()", "for key in record", "for value in record.values()", "for index in record"], correctIndex: 0, explanation: "items() yields key-value pairs that can be unpacked." },
        { id: "dictionaries-5", question: "Create profile = {name: Ava}, add age = 21, then print profile.", interactiveCode: true, initialCode: "# Write your code below\n", testCode: "assert profile == {'name': 'Ava', 'age': 21}", expectedOutput: "{'name': 'Ava', 'age': 21}", requiredCodePatterns: ["\\bprofile\\s*=\\s*\\{", "\\bprofile\\s*\\[", "\\bprint\\s*\\(\\s*profile\\s*\\)"], validationMessage: "Create profile with name Ava, add age 21 using its key, then print profile.", explanation: "Assignment through a new key adds a new key-value pair." },
      ]
    },
  ],
};

export const COLLECTIONS_MODULE_LESSON: LessonContent = {
  slug: "collections-module",
  title: "Collections Module",
  subtitle: "Use purpose-built containers for counting, grouping, queues, and layered settings.",
  sections: [
    { kind: "prose", heading: "Why the collections module matters", body: ["Python's `collections` module provides specialized containers for common data-organization tasks. They complement `lists`, `tuples`, `sets`, and `dictionaries` when the job has a clear pattern.", "`Counter` counts values, `defaultdict` supplies missing defaults, `OrderedDict` provides order-management methods, `deque` works efficiently at both ends, and `ChainMap` layers dictionaries into one view."] },
    { kind: "animation", variant: "collections-module", caption: "Choose a specialized collection when the operation matters as much as the stored values" },
    { kind: "syntax", title: "Import collection types", code: "from collections import Counter, defaultdict, OrderedDict, deque, ChainMap", description: "Import only the tools a program needs from Python's built-in collections module." },
    { kind: "table", caption: "Collections module at a glance", headers: ["Tool", "Best for", "Core idea"], rows: [["Counter", "Frequency counts", "Values become keys and counts become values"], ["defaultdict", "Grouping or counting", "Missing keys receive a default value"], ["OrderedDict", "Order-sensitive logic", "Move or remove pairs from either end"], ["deque", "Queues and stacks", "Fast additions and removals at both ends"], ["ChainMap", "Layered settings", "Search several dictionaries from left to right"]] },
    { kind: "prose", heading: "Counter", body: ["`Counter` is a **dictionary-like object** that counts how often each hashable value occurs. It is useful for character frequencies, votes, tags, inventory, and other repeated data.", "The counted values become keys and their frequencies become values. **Missing counts** read as **0**."] },
    { kind: "syntax", title: "Count an iterable", code: "from collections import Counter\ncounts = Counter(iterable)", description: "Pass a string, list, tuple, or another iterable to count its values." },
    { kind: "interactive-code", caption: "COUNTER · COUNT FREQUENCY", code: 'from collections import Counter\n\nletters = Counter("banana")\nfruit = Counter(["apple", "banana", "apple", "mango", "banana", "apple"])\n\nprint(letters)\nprint(fruit)\nprint(fruit["apple"])\nprint(fruit["pear"])' },
    { kind: "prose", heading: "Counter methods", body: ["Use `most_common(n)` to find the most frequent pairs. `update()` adds new counts, while `subtract()` removes counts. `elements()` repeats each item according to its positive count."] },
    { kind: "interactive-code", caption: "COUNTER · INSPECT AND UPDATE", code: 'from collections import Counter\n\nvotes = Counter(["A", "B", "A", "C", "A", "B"])\nprint(votes.most_common(2))\n\nvotes.update(["B", "B"])\nvotes.subtract(["A"])\n\nprint(votes)\nprint(list(votes.elements()))' },
    { kind: "prose", heading: "defaultdict", body: ["A `defaultdict` is a dictionary that creates a default value when a missing key is accessed. It prevents a `KeyError` when the default behavior is appropriate.", "Use `int` for counts that begin at 0, `list` to group values, and `set` to group unique values. Accessing a missing key creates that key with the default value."] },
    { kind: "syntax", title: "Create a defaultdict", code: "from collections import defaultdict\ncounts = defaultdict(int)\ngroups = defaultdict(list)", description: "The factory is called for a missing key. int() returns 0 and list() returns an empty list." },
    { kind: "interactive-code", caption: "DEFAULTDICT · COUNT AND GROUP", code: 'from collections import defaultdict\n\nmarks = defaultdict(int)\nmarks["math"] += 10\nmarks["science"] += 20\n\nstudents = defaultdict(list)\nstudents["Python"].append("Ava")\nstudents["Python"].append("Noah")\nstudents["SQL"].append("Mia")\n\nprint(dict(marks))\nprint(dict(students))' },
    { kind: "prose", heading: "OrderedDict", body: ["A normal Python dictionary preserves insertion order in modern Python. Use `OrderedDict` when the program needs its extra order-management methods, not merely ordered display.", "`move_to_end()` moves a chosen key to the beginning or end. `popitem(last=False)` removes the first item, while the default removes the last item."] },
    { kind: "syntax", title: "Manage dictionary order", code: "from collections import OrderedDict\nrecord = OrderedDict()\nrecord.move_to_end(key, last=False)\nfirst_pair = record.popitem(last=False)", description: "OrderedDict adds operations for intentionally changing or removing order." },
    { kind: "interactive-code", caption: "ORDEREDDICT · MOVE AND REMOVE", code: 'from collections import OrderedDict\n\nsteps = OrderedDict([("plan", 1), ("build", 2), ("ship", 3)])\nsteps.move_to_end("ship", last=False)\nfirst_step = steps.popitem(last=False)\n\nprint(first_step)\nprint(steps)' },
    { kind: "prose", heading: "deque", body: ["A `deque`, pronounced deck, is a double-ended queue. It supports fast additions and removals at the left and right ends, so it fits **queues, stacks, recent-history buffers, undo operations,** and **sliding windows**.", "A **list** is usually fine for **general storage**. Prefer a `deque` when **repeatedly removing from or inserting at the beginning**."] },
    { kind: "syntax", title: "Use a deque from either end", code: "from collections import deque\nqueue = deque(iterable)\nqueue.append(value)\nqueue.appendleft(value)\nright = queue.pop()\nleft = queue.popleft()", description: "append and pop work on the right. appendleft and popleft work on the left." },
    { kind: "interactive-code", caption: "DEQUE · QUEUE OPERATIONS", code: 'from collections import deque\n\nqueue = deque(["Ava", "Noah", "Mia"])\nqueue.append("Leo")\nqueue.appendleft("Ivy")\nnext_person = queue.popleft()\nlast_person = queue.pop()\n\nprint(next_person)\nprint(last_person)\nprint(queue)' },
    { kind: "prose", heading: "deque helpers", body: ["`extend()` adds several values on the right and `extendleft()` adds values on the left. Because each value is added to the left in turn, `extendleft()` reverses the iterable's visible order.", "`rotate(n)` shifts values right for positive n and left for negative n. A `deque` can also use `maxlen` to keep only a fixed amount of recent history."] },
    { kind: "interactive-code", caption: "DEQUE · ROTATE AND RECENT HISTORY", code: 'from collections import deque\n\nrecent = deque(["home", "search", "lesson"], maxlen=3)\nrecent.append("quiz")\nrecent.rotate(1)\n\nprint(recent)' },
    { kind: "prose", heading: "ChainMap", body: ["A `ChainMap` combines dictionaries into one lookup view without permanently merging them. It searches its dictionaries from left to right.", "This is useful for layered configuration: user settings can override defaults while the original dictionaries remain separate."] },
    { kind: "syntax", title: "Layer dictionaries with ChainMap", code: "from collections import ChainMap\nsettings = ChainMap(overrides, defaults)\nvalue = settings[key]", description: "The first mapping that contains the key supplies the value." },
    { kind: "interactive-code", caption: "CHAINMAP · USER SETTINGS OVER DEFAULTS", code: 'from collections import ChainMap\n\ndefaults = {"theme": "light", "language": "English", "font_size": 14}\nuser_settings = {"theme": "dark"}\nsettings = ChainMap(user_settings, defaults)\n\nprint(settings["theme"])\nprint(settings["language"])\nprint(settings.maps)\nprint(settings.new_child({"font_size": 18})["font_size"])' },
    { kind: "table", caption: "Choose the right tool", headers: ["Need", "Choose", "Why"], rows: [["Count repeated values", "Counter", "Keeps frequency data directly"], ["Append values under new group keys", "defaultdict(list)", "Avoids manual missing-key setup"], ["Move or remove dictionary pairs by order", "OrderedDict", "Adds explicit order-management methods"], ["Process a queue from the left", "deque", "popleft() is designed for this"], ["Overlay settings without merging", "ChainMap", "First matching mapping wins"]] },
    { kind: "callout", tone: "warn", title: "Common mistakes", body: "- **Using Counter for unhashable values**: its values must be hashable, so a list cannot be counted directly.\n- **Accessing a missing defaultdict key only to inspect it**: that access creates the key. Use get() when you do not want mutation.\n- **Choosing OrderedDict only for insertion order**: ordinary dictionaries already preserve insertion order in modern Python.\n- **Using list.pop(0) for a busy queue**: choose deque.popleft() for repeated left-side removal.\n- **Treating ChainMap as a merged dictionary**: it is a layered view, and lookup searches mappings from left to right." },
    { kind: "takeaways", items: ["The collections module supplies specialized containers for repeated data patterns.", "Counter handles frequency data, and defaultdict makes counting and grouping concise.", "OrderedDict is for explicit order-management methods beyond normal dictionary insertion order.", "deque is the natural choice for fast queue and stack operations at both ends.", "ChainMap layers dictionaries so overrides can take priority over defaults."] },
    {
      kind: "quiz", questions: [
        { id: "collections-1", question: "Which collection type counts how often values occur?", options: ["Counter", "ChainMap", "deque", "OrderedDict"], correctIndex: 0, explanation: "Counter maps each value to its frequency." },
        { id: "collections-2", question: "What default does defaultdict(int) create for a missing key?", options: ["0", "[]", "None", "KeyError"], correctIndex: 0, explanation: "int() returns 0, so defaultdict(int) starts missing counts at 0." },
        { id: "collections-3", question: "Which operation removes the next item from the left side of a queue deque?", options: ["popleft()", "pop()", "appendleft()", "rotate()"], correctIndex: 0, explanation: "popleft() removes and returns the leftmost deque value." },
        { id: "collections-4", question: "When ChainMap(overrides, defaults) finds a key in both mappings, which value is used?", options: ["The value in overrides", "The value in defaults", "Both values", "A KeyError"], correctIndex: 0, explanation: "ChainMap searches mappings from left to right, so the first match wins." },
        { id: "collections-5", question: "Create a Counter for the letters in banana, then print the count for a.", interactiveCode: true, initialCode: "# Write your code below\n", testCode: "assert counts['a'] == 3", expectedOutput: "3", requiredCodePatterns: ["from\\s+collections\\s+import\\s+Counter", "\\bcounts\\s*=\\s*Counter\\s*\\(", "\\bprint\\s*\\(\\s*counts\\s*\\[\\s*(['\\\"])a\\1\\s*\\]\\s*\\)"], validationMessage: "Import Counter, create counts from banana, then print counts['a'].", explanation: "Counter makes each character a key and stores its frequency as the value." },
      ]
    },
  ],
};

export const DATA_STRUCTURES_FINAL_QUIZ_LESSON: LessonContent = {
  slug: "data-structures-final-quiz",
  title: "Data Structures Final Quiz",
  subtitle: "Review lists, tuples, sets, dictionaries, and the collections module with fifteen questions.",
  sections: [
    {
      kind: "quiz",
      isFinalQuiz: true,
      questions: [
        {
          id: "data-structures-final-1",
          question: "What does numbers[1:4] return for numbers = [10, 20, 30, 40, 50]?",
          options: ["[20, 30, 40]", "[10, 20, 30, 40]", "[20, 30, 40, 50]", "[10, 40]"],
          correctIndex: 0,
          explanation: "A slice includes the start index and stops before the end index.",
        },
        {
          id: "data-structures-final-2",
          question: "Which statement creates a new shallow copy of a list named items?",
          options: ["items.copy()", "alias = items", "items.clear()", "items.sort()"],
          correctIndex: 0,
          explanation: "copy() creates a new outer list. Assignment only creates another name for the same list.",
        },
        {
          id: "data-structures-final-3",
          question: "Create tasks with plan and build, append ship, then print tasks.",
          interactiveCode: true,
          initialCode: "# Write your code below\n",
          testCode: "assert tasks == ['plan', 'build', 'ship']",
          expectedOutput: "['plan', 'build', 'ship']",
          requiredCodePatterns: [
            "\\btasks\\s*=\\s*\\[\\s*(['\\\"])plan\\1\\s*,\\s*(['\\\"])build\\2\\s*\\]",
            "\\btasks\\.append\\s*\\(\\s*(['\\\"])ship\\1\\s*\\)",
            "\\bprint\\s*\\(\\s*tasks\\s*\\)",
          ],
          validationMessage: "Create the list, use tasks.append('ship'), then print tasks.",
          explanation: "append() adds one item to the end of an existing list.",
        },
        {
          id: "data-structures-final-4",
          question: "Why can a tuple be used as a dictionary key when its contents are immutable?",
          options: ["It is hashable", "It is always sorted", "It is a list", "It automatically becomes a string"],
          correctIndex: 0,
          explanation: "Immutable tuples are hashable, so they can be used as dictionary keys or set values.",
        },
        {
          id: "data-structures-final-5",
          question: 'What does first, second = ("Ava", "Noah") assign to first?',
          options: ["Ava", "Noah", "(Ava, Noah)", "It raises an error"],
          correctIndex: 0,
          explanation: "Tuple unpacking assigns values by position.",
        },
        {
          id: "data-structures-final-6",
          question: "Which expression creates an empty set?",
          options: ["set()", "{}", "[]", "()"],
          correctIndex: 0,
          explanation: "set() creates an empty set. Empty braces create an empty dictionary.",
        },
        {
          id: "data-structures-final-7",
          question: "Which operator keeps only values shared by two sets?",
          options: ["&", "|", "-", "^"],
          correctIndex: 0,
          explanation: "The intersection operator, &, keeps values found in both sets.",
        },
        {
          id: "data-structures-final-8",
          question: 'What does profile.get("city", "Unknown") return when city is not a key?',
          options: ["Unknown", "KeyError", "None only", "An empty dictionary"],
          correctIndex: 0,
          explanation: "get() returns its supplied fallback when the requested key is absent.",
        },
        {
          id: "data-structures-final-9",
          question: "Which tool creates an independent copy of nested mutable values in a dictionary?",
          options: ["copy.deepcopy()", "record.copy()", "alias = record", "dict.keys()"],
          correctIndex: 0,
          explanation: "deepcopy() recursively copies nested mutable objects. copy() only creates a new outer dictionary.",
        },
        {
          id: "data-structures-final-10",
          question: 'Create profile with name Ava and age 21. Update age to 22, then print profile["age"].',
          interactiveCode: true,
          initialCode: "# Write your code below\n",
          testCode: "assert profile == {'name': 'Ava', 'age': 22}",
          expectedOutput: "22",
          requiredCodePatterns: [
            "\\bprofile\\s*=\\s*\\{",
            "\\bprofile\\s*\\[\\s*(['\\\"])age\\1\\s*\\]\\s*=\\s*22\\b",
            "\\bprint\\s*\\(\\s*profile\\s*\\[\\s*(['\\\"])age\\1\\s*\\]\\s*\\)",
          ],
          validationMessage: "Create profile, update its age through the age key, then print profile['age'].",
          explanation: "Assignment through an existing dictionary key replaces that value.",
        },
        {
          id: "data-structures-final-11",
          question: "Which collection type counts how often each value occurs?",
          options: ["Counter", "deque", "ChainMap", "OrderedDict"],
          correctIndex: 0,
          explanation: "Counter stores each distinct value as a key and its frequency as the value.",
        },
        {
          id: "data-structures-final-12",
          question: "What default value does defaultdict(list) provide for a new key?",
          options: ["An empty list", "0", "None", "A KeyError"],
          correctIndex: 0,
          explanation: "list() creates an empty list, which defaultdict stores for the missing key.",
        },
        {
          id: "data-structures-final-13",
          question: "Which OrderedDict method moves a chosen key to the beginning?",
          options: ["move_to_end(key, last=False)", "popitem(last=False)", "update(key)", "keys(last=False)"],
          correctIndex: 0,
          explanation: "move_to_end(key, last=False) places the key at the beginning of an OrderedDict.",
        },
        {
          id: "data-structures-final-14",
          question: "Which deque method removes and returns the leftmost queue item?",
          options: ["popleft()", "pop()", "appendleft()", "rotate()"],
          correctIndex: 0,
          explanation: "popleft() is the queue operation for removing the value at the left end.",
        },
        {
          id: "data-structures-final-15",
          question: "Create defaults with theme light and language English, plus user_settings with theme dark. Use ChainMap so settings prints dark for theme.",
          interactiveCode: true,
          initialCode: "# Write your code below\n",
          testCode: "assert settings['theme'] == 'dark'\nassert settings['language'] == 'English'",
          expectedOutput: "dark",
          requiredCodePatterns: [
            "from\\s+collections\\s+import\\s+ChainMap",
            "\\bdefaults\\s*=\\s*\\{",
            "\\buser_settings\\s*=\\s*\\{",
            "\\bsettings\\s*=\\s*ChainMap\\s*\\(\\s*user_settings\\s*,\\s*defaults\\s*\\)",
            "\\bprint\\s*\\(\\s*settings\\s*\\[\\s*(['\\\"])theme\\1\\s*\\]\\s*\\)",
          ],
          validationMessage: "Import ChainMap, create both dictionaries including language in defaults, layer user_settings before defaults, then print settings['theme'].",
          explanation: "ChainMap checks user_settings first, so its dark theme overrides the light default.",
        },
      ],
    },
  ],
};

export const DATA_STRUCTURES_TOPICS: Record<string, { title: string; slug: string; lessons: LessonContent[] }> = {
  "data-structures": {
    title: "Data Structures",
    slug: "data-structures",
    lessons: [LISTS_LESSON, TUPLES_LESSON, SETS_LESSON, DICTIONARIES_LESSON, COLLECTIONS_MODULE_LESSON, DATA_STRUCTURES_FINAL_QUIZ_LESSON],
  },
};
