import { type LessonContent } from "@/lessons/types";

import gadgetGroveIntroImg from "@/images/datawarehouse/foundations/gadget-grove-intro.png";
import gadgetGroveImg from "@/images/datawarehouse/foundations/gadget-grove.png";
import journeyOfDataImg from "@/images/datawarehouse/foundations/journey-of-data.png";
import olapVsOltpImg from "@/images/datawarehouse/foundations/olap_vs_oltp.png";
import threeWaysToStoreImg from "@/images/datawarehouse/foundations/three-ways-to-store-data.png";
import dataMartImg from "@/images/datawarehouse/foundations/data-mart.png";
import dataMeshImg from "@/images/datawarehouse/foundations/data-mesh.png";
import dataFabricImg from "@/images/datawarehouse/foundations/data-fabric.png";
import underTheHoodImg from "@/images/datawarehouse/foundations/under_the_hood.png";

const dataJourney: LessonContent = {
  slug: "data-journey",
  title: "The Journey of Data",
  subtitle: "From Raw Signal to Actionable Insight.",
  sections: [
    {
      kind: "prose",
      heading: "Every Click Creates Data",
      body: [
        "We live in a world of immense data, generated every second from countless sources: Mobile & Web Apps, Smart Devices (tracking steps), IoT Sensors (temperature in a warehouse), and Social Media.",
        "To understand how businesses manage this, consider a fictional e-commerce company: Gadget Grove.",
      ],
    },
    {
      kind: "image",
      src: gadgetGroveIntroImg,
      alt: "Gadget Grove Introduction",
      caption: "An example e-commerce company's data sources",
    },
    {
      kind: "animation",
      variant: "dw-data-journey",
      caption: "The end-to-end data engineering pipeline",
    },
    {
      kind: "prose",
      heading: "The 5 Stages of the Data Pipeline",
      body: [
        "**1. Source**: Data is generated by applications, devices, and sensors.",
        "**2. Collect**: Raw data is captured in initial systems like operational databases or message brokers.",
        "**3. Process (ETL/ELT)**: Data is Extracted, Transformed (cleaned, enriched, aggregated), and Loaded into an analytical system.",
        "**4. Store**: Processed data is housed in purpose-built repositories like Data Warehouses or Lakehouses.",
        "**5. Analyse & Consume**: Data is used to power dashboards, run SQL queries, generate reports, or train machine learning models.",
      ],
    },
    {
      kind: "image",
      src: journeyOfDataImg,
      alt: "The Journey of Data",
      caption: "The 5 Stages of the Data Pipeline"
    },
  ],
};

const oltpVsOlap: LessonContent = {
  slug: "oltp-vs-olap",
  title: "OLTP vs. OLAP",
  subtitle: "Running the Business vs. Analyzing the Business.",
  sections: [
    {
      kind: "prose",
      heading: "The Two Worlds of Data",
      body: [
        "Modern businesses rely on two distinct types of data systems: **OLTP** handles real-time, day-to-day operations, while **OLAP** is used for in-depth analysis and strategic decision-making.",
      ],
    },
    {
      kind: "image",
      src: olapVsOltpImg,
      alt: "OLTP vs OLAP",
      caption: "The flow from operational systems to analytical systems",
    },
    {
      kind: "animation",
      variant: "dw-oltp-vs-olap",
      caption: "Comparing operational vs analytical databases",
    },
    {
      kind: "prose",
      heading: "OLTP: Running the Business",
      body: [
        "Think of it as the Cash Register. It captures and stores transaction data in real-time. If it goes down, business stops.",
        "**Key Characteristics**: High concurrency, simple fast queries (insert order, get balance), millisecond response times. Examples: MySQL, PostgreSQL, Oracle.",
      ],
    },
    {
      kind: "prose",
      heading: "OLAP: Analyzing the Business",
      body: [
        "Think of it as the Strategy Room. Here, managers review huge amounts of historical data to plan for growth.",
        "**Key Characteristics**: Fewer users (analysts), complex queries with joins and aggregations, response time in seconds to hours. Examples: Amazon Redshift, Google BigQuery, Snowflake.",
      ],
    },
    {
      kind: "prose",
      heading: "The Performance Challenge",
      body: [
        "Why not run analytics on the live system? Running complex, long-running OLAP queries directly on an OLTP database causes resource contention and crashes.",
        "OLTP databases are normalised for fast writes. Analytics require denormalised reads. Therefore, a separate, optimised system is required.",
      ],
    },
  ],
};

const analyticalStorage: LessonContent = {
  slug: "analytical-storage",
  title: "Storing Analytical Data",
  subtitle: "Data Warehouses, Data Lakes, and Lakehouses.",
  sections: [
    {
      kind: "prose",
      heading: "The Big Three",
      body: [
        "To analyze data without slowing down operations, data is moved into specialized analytical storage systems. There are three main architectures.",
      ],
    },
    {
      kind: "image",
      src: threeWaysToStoreImg,
      alt: "Three ways to store data",
      caption: "Data Warehouses, Data Lakes, and Lakehouses",
    },
    {
      kind: "animation",
      variant: "dw-storage-types",
      caption: "Warehouse vs Lake vs Lakehouse",
    },
    {
      kind: "prose",
      heading: "The Data Warehouse (The Library)",
      body: [
        "Data is collected, cleaned, structured, and put on the correct shelf. It uses a **schema-on-write** approach.",
        "Optimized for fast, complex queries for Business Intelligence (BI). It only stores structured, analytics-ready data. Very high performance but higher cost.",
      ],
    },
    {
      kind: "prose",
      heading: "The Data Lake (The Garage)",
      body: [
        "A vast repository that holds raw data in its native format (structured, semi-structured, unstructured). You just dump everything into it.",
        "It uses **schema-on-read**. Highly cost-effective for huge volumes, great for Machine Learning models that need raw, unfiltered data.",
      ],
    },
    {
      kind: "prose",
      heading: "The Data Lakehouse (The Modern Workshop)",
      body: [
        "A new, open architecture that combines the low-cost, flexible storage of a data lake with the data management and ACID transactions of a data warehouse.",
        "It acts as a single platform for both BI and AI workloads, eliminating data silos.",
      ],
    },
  ],
};

const organizingData: LessonContent = {
  slug: "organizing-data",
  title: "Organizing the Landscape",
  subtitle: "Data Marts, Data Mesh, and Data Fabric.",
  sections: [
    {
      kind: "prose",
      heading: "Managing Growth",
      body: [
        "As organizations grow, they face a new challenge: how to organize massive amounts of data so different teams can use it effectively without creating chaos.",
      ],
    },
    {
      kind: "animation",
      variant: "dw-organizing-data",
      caption: "Architectural patterns defining ownership and access",
    },
    {
      kind: "prose",
      heading: "Data Mart: The Departmental Bookshelf",
      body: [
        "A subset of a data warehouse focused on a particular department (e.g., Marketing or Finance). It provides a specific team with faster, simpler access to relevant data.",
      ],
    },
    {
      kind: "image",
      src: dataMartImg,
      alt: "Data Mart",
      caption: "A Data Mart focuses on a specific business line",
    },
    {
      kind: "prose",
      heading: "Data Mesh: Decentralized Ownership",
      body: [
        "For very large enterprises, central data teams become bottlenecks. Data Mesh is a decentralized data architecture where data is treated as a product and owned by the teams that know it best.",
        "It's primarily a new Culture and Operating Model: Every department builds and owns its own library.",
      ],
    },
    {
      kind: "image",
      src: dataMeshImg,
      alt: "Data Mesh",
      caption: "Data Mesh distributes ownership to domain teams",
    },
    {
      kind: "prose",
      heading: "Data Fabric: A Universal Library Card",
      body: [
        "A loosely coupled architecture that connects all of an organization's data across different silos and locations.",
        "It's an Architecture and Technology Layer: It uses data virtualization to let analysts find and access data without needing to know where it's stored physically.",
      ],
    },
    {
      kind: "image",
      src: dataFabricImg,
      alt: "Data Fabric",
      caption: "Data Fabric provides a unified access layer across silos",
    },
  ],
};

const databaseEngines: LessonContent = {
  slug: "database-engines",
  title: "Under the Hood: Database Engines",
  subtitle: "The many families of databases.",
  sections: [
    {
      kind: "prose",
      heading: "The Two Main Families: SQL vs. NoSQL",
      body: [
        "**Relational Databases (SQL)** are like an organized spreadsheet. Data must fit predefined columns and rows. Uses rigid schemas and guarantees strong consistency (ACID). Best for financial transactions.",
        "**NoSQL Databases** are like flexible digital folders holding different types of information. Optimized for specific data models, scale, and rapid iteration.",
      ],
    },
    {
      kind: "image",
      src: underTheHoodImg,
      alt: "Under the Hood: Database Engines",
      caption: "Relational (SQL) vs non-relational (NoSQL) database families",
    },
    {
      kind: "animation",
      variant: "dw-database-families",
      caption: "Exploring the NoSQL family",
    },
    {
      kind: "prose",
      heading: "A Quick Tour of the NoSQL Family",
      body: [
        "• **Document Store**: Stores data in flexible, self-contained documents (JSON). Great for product catalogs. Example: MongoDB.",
        "• **Key-Value Store**: A simple dictionary or hashmap. Extremely fast for lookups. Great for caching. Example: Redis.",
        "• **Wide-Column Store**: A super-spreadsheet for massive datasets like IoT time-series. Example: Cassandra.",
        "• **Graph Database**: Designed to navigate complex relationships (nodes and edges). Great for fraud detection. Example: Neo4j.",
      ],
    },
    {
      kind: "prose",
      heading: "The New Frontier",
      body: [
        "• **Vector Databases**: Organize data by meaning and context, storing data as numerical vectors. Essential for AI and similarity search.",
        "• **Multi-Model Databases**: A 'Swiss Army Knife' database that can store and query data using multiple models (document, graph, key-value) simultaneously.",
      ],
    },
  ],
};

const dataWarehouses: LessonContent = {
  slug: "data-warehouses",
  title: "Data Warehouses",
  subtitle: "Understanding Data Warehouses.",
  sections: [
    {
      kind: "prose",
      heading: "Coming Soon",
      body: ["Content for this lesson will be added soon!"],
    },
  ],
};

const csvJson: LessonContent = {
  slug: "human-readable",
  title: "Human-Readable Formats",
  subtitle: "CSV & JSON.",
  sections: [
    {
      kind: "prose",
      heading: "Coming Soon",
      body: ["Content for this lesson will be added soon!"],
    },
  ],
};

const parquetOrc: LessonContent = {
  slug: "columnar-formats",
  title: "Row vs. Columnar",
  subtitle: "Avro, Parquet & ORC.",
  sections: [
    {
      kind: "prose",
      heading: "Coming Soon",
      body: ["Content for this lesson will be added soon!"],
    },
  ],
};

const openTable: LessonContent = {
  slug: "open-table-formats",
  title: "Open Table Formats",
  subtitle: "Iceberg, Delta Lake & Hudi.",
  sections: [
    {
      kind: "prose",
      heading: "Coming Soon",
      body: ["Content for this lesson will be added soon!"],
    },
  ],
};

export const FOUNDATION_TOPICS: Record<
  string,
  { title: string; blurb: string; slug: string; lessons: LessonContent[] }
> = {
  "data-ecosystems": {
    title: "Data Ecosystems",
    slug: "data-ecosystems",
    blurb: "From transaction processing (OLTP) to analytical datastores (OLAP) and distributed meshes.",
    lessons: [dataJourney, oltpVsOlap, analyticalStorage, organizingData, databaseEngines, dataWarehouses],
  },
  "data-formats": {
    title: "Data Formats & Storage",
    slug: "data-formats",
    blurb: "Understanding how data is stored, compressed, and managed at scale.",
    lessons: [csvJson, parquetOrc, openTable],
  },
};
