/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SqlIndexRouteImport } from './routes/sql.index'
import { Route as PatternsIndexRouteImport } from './routes/patterns.index'
import { Route as TracksTrackRouteImport } from './routes/tracks.$track'
import { Route as PatternsPatternRouteImport } from './routes/patterns.$pattern'
import { Route as PatternsPatternIndexRouteImport } from './routes/patterns.$pattern.index'
import { Route as SqlQueryingTopicRouteImport } from './routes/sql.querying.$topic'
import { Route as SqlFoundationsTopicRouteImport } from './routes/sql.foundations.$topic'
import { Route as PatternsPatternLessonRouteImport } from './routes/patterns.$pattern.$lesson'
import { Route as SqlQueryingTopicIndexRouteImport } from './routes/sql.querying.$topic.index'
import { Route as SqlFoundationsTopicIndexRouteImport } from './routes/sql.foundations.$topic.index'
import { Route as SqlQueryingTopicLessonRouteImport } from './routes/sql.querying.$topic.$lesson'
import { Route as SqlFoundationsTopicLessonRouteImport } from './routes/sql.foundations.$topic.$lesson'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlIndexRoute = SqlIndexRouteImport.update({
  id: '/sql/',
  path: '/sql/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsIndexRoute = PatternsIndexRouteImport.update({
  id: '/patterns/',
  path: '/patterns/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksTrackRoute = TracksTrackRouteImport.update({
  id: '/tracks/$track',
  path: '/tracks/$track',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsPatternRoute = PatternsPatternRouteImport.update({
  id: '/patterns/$pattern',
  path: '/patterns/$pattern',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsPatternIndexRoute = PatternsPatternIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatternsPatternRoute,
} as any)
const SqlQueryingTopicRoute = SqlQueryingTopicRouteImport.update({
  id: '/sql/querying/$topic',
  path: '/sql/querying/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlFoundationsTopicRoute = SqlFoundationsTopicRouteImport.update({
  id: '/sql/foundations/$topic',
  path: '/sql/foundations/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsPatternLessonRoute = PatternsPatternLessonRouteImport.update({
  id: '/$lesson',
  path: '/$lesson',
  getParentRoute: () => PatternsPatternRoute,
} as any)
const SqlQueryingTopicIndexRoute = SqlQueryingTopicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SqlQueryingTopicRoute,
} as any)
const SqlFoundationsTopicIndexRoute =
  SqlFoundationsTopicIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SqlFoundationsTopicRoute,
  } as any)
const SqlQueryingTopicLessonRoute = SqlQueryingTopicLessonRouteImport.update({
  id: '/$lesson',
  path: '/$lesson',
  getParentRoute: () => SqlQueryingTopicRoute,
} as any)
const SqlFoundationsTopicLessonRoute =
  SqlFoundationsTopicLessonRouteImport.update({
    id: '/$lesson',
    path: '/$lesson',
    getParentRoute: () => SqlFoundationsTopicRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/patterns/$pattern': typeof PatternsPatternRouteWithChildren
  '/tracks/$track': typeof TracksTrackRoute
  '/patterns/': typeof PatternsIndexRoute
  '/sql/': typeof SqlIndexRoute
  '/patterns/$pattern/$lesson': typeof PatternsPatternLessonRoute
  '/sql/foundations/$topic': typeof SqlFoundationsTopicRouteWithChildren
  '/sql/querying/$topic': typeof SqlQueryingTopicRouteWithChildren
  '/patterns/$pattern/': typeof PatternsPatternIndexRoute
  '/sql/foundations/$topic/$lesson': typeof SqlFoundationsTopicLessonRoute
  '/sql/querying/$topic/$lesson': typeof SqlQueryingTopicLessonRoute
  '/sql/foundations/$topic/': typeof SqlFoundationsTopicIndexRoute
  '/sql/querying/$topic/': typeof SqlQueryingTopicIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tracks/$track': typeof TracksTrackRoute
  '/patterns': typeof PatternsIndexRoute
  '/sql': typeof SqlIndexRoute
  '/patterns/$pattern/$lesson': typeof PatternsPatternLessonRoute
  '/patterns/$pattern': typeof PatternsPatternIndexRoute
  '/sql/foundations/$topic/$lesson': typeof SqlFoundationsTopicLessonRoute
  '/sql/querying/$topic/$lesson': typeof SqlQueryingTopicLessonRoute
  '/sql/foundations/$topic': typeof SqlFoundationsTopicIndexRoute
  '/sql/querying/$topic': typeof SqlQueryingTopicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/patterns/$pattern': typeof PatternsPatternRouteWithChildren
  '/tracks/$track': typeof TracksTrackRoute
  '/patterns/': typeof PatternsIndexRoute
  '/sql/': typeof SqlIndexRoute
  '/patterns/$pattern/$lesson': typeof PatternsPatternLessonRoute
  '/sql/foundations/$topic': typeof SqlFoundationsTopicRouteWithChildren
  '/sql/querying/$topic': typeof SqlQueryingTopicRouteWithChildren
  '/patterns/$pattern/': typeof PatternsPatternIndexRoute
  '/sql/foundations/$topic/$lesson': typeof SqlFoundationsTopicLessonRoute
  '/sql/querying/$topic/$lesson': typeof SqlQueryingTopicLessonRoute
  '/sql/foundations/$topic/': typeof SqlFoundationsTopicIndexRoute
  '/sql/querying/$topic/': typeof SqlQueryingTopicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/patterns/$pattern'
    | '/tracks/$track'
    | '/patterns/'
    | '/sql/'
    | '/patterns/$pattern/$lesson'
    | '/sql/foundations/$topic'
    | '/sql/querying/$topic'
    | '/patterns/$pattern/'
    | '/sql/foundations/$topic/$lesson'
    | '/sql/querying/$topic/$lesson'
    | '/sql/foundations/$topic/'
    | '/sql/querying/$topic/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tracks/$track'
    | '/patterns'
    | '/sql'
    | '/patterns/$pattern/$lesson'
    | '/patterns/$pattern'
    | '/sql/foundations/$topic/$lesson'
    | '/sql/querying/$topic/$lesson'
    | '/sql/foundations/$topic'
    | '/sql/querying/$topic'
  id:
    | '__root__'
    | '/'
    | '/patterns/$pattern'
    | '/tracks/$track'
    | '/patterns/'
    | '/sql/'
    | '/patterns/$pattern/$lesson'
    | '/sql/foundations/$topic'
    | '/sql/querying/$topic'
    | '/patterns/$pattern/'
    | '/sql/foundations/$topic/$lesson'
    | '/sql/querying/$topic/$lesson'
    | '/sql/foundations/$topic/'
    | '/sql/querying/$topic/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PatternsPatternRoute: typeof PatternsPatternRouteWithChildren
  TracksTrackRoute: typeof TracksTrackRoute
  PatternsIndexRoute: typeof PatternsIndexRoute
  SqlIndexRoute: typeof SqlIndexRoute
  SqlFoundationsTopicRoute: typeof SqlFoundationsTopicRouteWithChildren
  SqlQueryingTopicRoute: typeof SqlQueryingTopicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql/': {
      id: '/sql/'
      path: '/sql'
      fullPath: '/sql/'
      preLoaderRoute: typeof SqlIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns/': {
      id: '/patterns/'
      path: '/patterns'
      fullPath: '/patterns/'
      preLoaderRoute: typeof PatternsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks/$track': {
      id: '/tracks/$track'
      path: '/tracks/$track'
      fullPath: '/tracks/$track'
      preLoaderRoute: typeof TracksTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns/$pattern': {
      id: '/patterns/$pattern'
      path: '/patterns/$pattern'
      fullPath: '/patterns/$pattern'
      preLoaderRoute: typeof PatternsPatternRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns/$pattern/': {
      id: '/patterns/$pattern/'
      path: '/'
      fullPath: '/patterns/$pattern/'
      preLoaderRoute: typeof PatternsPatternIndexRouteImport
      parentRoute: typeof PatternsPatternRoute
    }
    '/sql/querying/$topic': {
      id: '/sql/querying/$topic'
      path: '/sql/querying/$topic'
      fullPath: '/sql/querying/$topic'
      preLoaderRoute: typeof SqlQueryingTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql/foundations/$topic': {
      id: '/sql/foundations/$topic'
      path: '/sql/foundations/$topic'
      fullPath: '/sql/foundations/$topic'
      preLoaderRoute: typeof SqlFoundationsTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns/$pattern/$lesson': {
      id: '/patterns/$pattern/$lesson'
      path: '/$lesson'
      fullPath: '/patterns/$pattern/$lesson'
      preLoaderRoute: typeof PatternsPatternLessonRouteImport
      parentRoute: typeof PatternsPatternRoute
    }
    '/sql/querying/$topic/': {
      id: '/sql/querying/$topic/'
      path: '/'
      fullPath: '/sql/querying/$topic/'
      preLoaderRoute: typeof SqlQueryingTopicIndexRouteImport
      parentRoute: typeof SqlQueryingTopicRoute
    }
    '/sql/foundations/$topic/': {
      id: '/sql/foundations/$topic/'
      path: '/'
      fullPath: '/sql/foundations/$topic/'
      preLoaderRoute: typeof SqlFoundationsTopicIndexRouteImport
      parentRoute: typeof SqlFoundationsTopicRoute
    }
    '/sql/querying/$topic/$lesson': {
      id: '/sql/querying/$topic/$lesson'
      path: '/$lesson'
      fullPath: '/sql/querying/$topic/$lesson'
      preLoaderRoute: typeof SqlQueryingTopicLessonRouteImport
      parentRoute: typeof SqlQueryingTopicRoute
    }
    '/sql/foundations/$topic/$lesson': {
      id: '/sql/foundations/$topic/$lesson'
      path: '/$lesson'
      fullPath: '/sql/foundations/$topic/$lesson'
      preLoaderRoute: typeof SqlFoundationsTopicLessonRouteImport
      parentRoute: typeof SqlFoundationsTopicRoute
    }
  }
}

interface PatternsPatternRouteChildren {
  PatternsPatternLessonRoute: typeof PatternsPatternLessonRoute
  PatternsPatternIndexRoute: typeof PatternsPatternIndexRoute
}

const PatternsPatternRouteChildren: PatternsPatternRouteChildren = {
  PatternsPatternLessonRoute: PatternsPatternLessonRoute,
  PatternsPatternIndexRoute: PatternsPatternIndexRoute,
}

const PatternsPatternRouteWithChildren = PatternsPatternRoute._addFileChildren(
  PatternsPatternRouteChildren,
)

interface SqlFoundationsTopicRouteChildren {
  SqlFoundationsTopicLessonRoute: typeof SqlFoundationsTopicLessonRoute
  SqlFoundationsTopicIndexRoute: typeof SqlFoundationsTopicIndexRoute
}

const SqlFoundationsTopicRouteChildren: SqlFoundationsTopicRouteChildren = {
  SqlFoundationsTopicLessonRoute: SqlFoundationsTopicLessonRoute,
  SqlFoundationsTopicIndexRoute: SqlFoundationsTopicIndexRoute,
}

const SqlFoundationsTopicRouteWithChildren =
  SqlFoundationsTopicRoute._addFileChildren(SqlFoundationsTopicRouteChildren)

interface SqlQueryingTopicRouteChildren {
  SqlQueryingTopicLessonRoute: typeof SqlQueryingTopicLessonRoute
  SqlQueryingTopicIndexRoute: typeof SqlQueryingTopicIndexRoute
}

const SqlQueryingTopicRouteChildren: SqlQueryingTopicRouteChildren = {
  SqlQueryingTopicLessonRoute: SqlQueryingTopicLessonRoute,
  SqlQueryingTopicIndexRoute: SqlQueryingTopicIndexRoute,
}

const SqlQueryingTopicRouteWithChildren =
  SqlQueryingTopicRoute._addFileChildren(SqlQueryingTopicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PatternsPatternRoute: PatternsPatternRouteWithChildren,
  TracksTrackRoute: TracksTrackRoute,
  PatternsIndexRoute: PatternsIndexRoute,
  SqlIndexRoute: SqlIndexRoute,
  SqlFoundationsTopicRoute: SqlFoundationsTopicRouteWithChildren,
  SqlQueryingTopicRoute: SqlQueryingTopicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
